namespace Views.Forms;

partial class MainView : Krypton.Toolkit.KryptonForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.tabControl = new System.Windows.Forms.TabControl();
        this.topSpacer = new Krypton.Toolkit.KryptonPanel();
        this.sideBar = new Krypton.Toolkit.KryptonPanel();
        this.sideStrip = new Krypton.Toolkit.KryptonPanel();
        this.cardFiles = new Krypton.Toolkit.KryptonPanel();
        this.cardSynced = new Krypton.Toolkit.KryptonPanel();
        this.cardPending = new Krypton.Toolkit.KryptonPanel();
        this.cardServers = new Krypton.Toolkit.KryptonPanel();
        this.lblDashTitle = new Krypton.Toolkit.KryptonLabel();
        this.picUserAvatar = new System.Windows.Forms.PictureBox();
        this.lblUserBadge = new Krypton.Toolkit.KryptonLabel();
        this.tabDashboard = new System.Windows.Forms.TabPage();
        this.tabSync = new System.Windows.Forms.TabPage();
        this.tabServers = new System.Windows.Forms.TabPage();
        this.tabAudit = new System.Windows.Forms.TabPage();
        this.tabAnalytics = new System.Windows.Forms.TabPage();
        this.tabUsers = new System.Windows.Forms.TabPage();
        this.tabBackup = new System.Windows.Forms.TabPage();
        this.tabTrash = new System.Windows.Forms.TabPage();
        this.tabSettings = new System.Windows.Forms.TabPage();
        this.btnEditServer = new Krypton.Toolkit.KryptonButton();
        this.btnSetActive = new Krypton.Toolkit.KryptonButton();
        this.btnDeleteServer = new Krypton.Toolkit.KryptonButton();
        this.btnAddUser = new Krypton.Toolkit.KryptonButton();
        this.btnDeleteUser = new Krypton.Toolkit.KryptonButton();
        this.gridUsers = new Krypton.Toolkit.KryptonDataGridView();
        this.btnSelectFolder = new Krypton.Toolkit.KryptonButton();
        this.btnSync = new Krypton.Toolkit.KryptonButton();
        this.btnDelete = new Krypton.Toolkit.KryptonButton();
        this.btnResume = new Krypton.Toolkit.KryptonButton();
        this.btnExplorer = new Krypton.Toolkit.KryptonButton();
        this.btnLogout = new Krypton.Toolkit.KryptonButton();
        this.lblStatus = new Krypton.Toolkit.KryptonLabel();
        this.gridFiles = new Krypton.Toolkit.KryptonDataGridView();
        this.notifyIcon = new System.Windows.Forms.NotifyIcon();
        this.components = new System.ComponentModel.Container();
        this.btnAddServer = new Krypton.Toolkit.KryptonButton();
        this.gridServers = new Krypton.Toolkit.KryptonDataGridView();
        this.gridAudit = new Krypton.Toolkit.KryptonDataGridView();
        this.txtAuditFilter = new Krypton.Toolkit.KryptonTextBox();
        this.btnExportAudit = new Krypton.Toolkit.KryptonButton();
        this.lblAnalytics = new Krypton.Toolkit.KryptonLabel();
        this.tabControl.SuspendLayout();
        this.tabDashboard.SuspendLayout();
        this.tabSync.SuspendLayout();
        this.tabServers.SuspendLayout();
        this.tabAudit.SuspendLayout();
        this.tabAnalytics.SuspendLayout();
        this.tabBackup.SuspendLayout();
        this.tabTrash.SuspendLayout();
        this.tabSettings.SuspendLayout();
        this.sideBar.SuspendLayout();
        this.sideStrip.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)(this.gridFiles)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridServers)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridAudit)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).BeginInit();
        this.sideBar.SuspendLayout();
        this.SuspendLayout();

        this.sideBar.Controls.Add(this.picSideLogo);
        this.sideBar.Controls.Add(this.lblSideTitle);
        this.sideBar.Controls.Add(this.btnNavToggle);
        this.sideBar.Controls.Add(this.navDashboard);
        this.sideBar.Controls.Add(this.navSync);
        this.sideBar.Controls.Add(this.navBackup);
        this.sideBar.Controls.Add(this.navTrash);
        this.sideBar.Controls.Add(this.navServers);
        this.sideBar.Controls.Add(this.navAudit);
        this.sideBar.Controls.Add(this.navAnalytics);
        this.sideBar.Controls.Add(this.navUsers);
        this.sideBar.Controls.Add(this.navSettings);
        this.sideBar.Controls.Add(this.lblTreeCap);
        this.sideBar.Controls.Add(this.treeFiles);
        this.sideBar.Dock = System.Windows.Forms.DockStyle.Left;
        this.sideBar.Location = new System.Drawing.Point(0, 0);
        this.sideBar.Name = "sideBar";
        this.sideBar.Size = new System.Drawing.Size(240, 640);
        this.sideBar.TabIndex = 4;

        this.picSideLogo = new System.Windows.Forms.PictureBox();
        ((System.ComponentModel.ISupportInitialize)(this.picSideLogo)).BeginInit();
        this.picSideLogo.Location = new System.Drawing.Point(12, 70);
        this.picSideLogo.Name = "picSideLogo";
        this.picSideLogo.Size = new System.Drawing.Size(40, 40);
        this.picSideLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
        this.picSideLogo.TabIndex = 0;
        this.picSideLogo.TabStop = false;
        ((System.ComponentModel.ISupportInitialize)(this.picSideLogo)).EndInit();

        this.lblSideTitle = new Krypton.Toolkit.KryptonLabel();
        this.lblSideTitle.AutoSize = true;
        this.lblSideTitle.Location = new System.Drawing.Point(58, 80);
        this.lblSideTitle.Name = "lblSideTitle";
        this.lblSideTitle.Text = "DataSync";

        this.btnNavToggle = new Krypton.Toolkit.KryptonButton();
        this.btnNavToggle.AutoSize = false;
        this.btnNavToggle.Location = new System.Drawing.Point(196, 72);
        this.btnNavToggle.Name = "btnNavToggle";
        this.btnNavToggle.Size = new System.Drawing.Size(32, 36);
        this.btnNavToggle.TabIndex = 1;
        this.btnNavToggle.Text = "«";
        this.btnNavToggle.ButtonStyle = Krypton.Toolkit.ButtonStyle.ListItem;
        this.btnNavToggle.Click += new System.EventHandler(this.btnNavToggle_Click);

        this.navDashboard = new Krypton.Toolkit.KryptonButton();
        this.navSync = new Krypton.Toolkit.KryptonButton();
        this.navBackup = new Krypton.Toolkit.KryptonButton();
        this.navTrash = new Krypton.Toolkit.KryptonButton();
        this.navServers = new Krypton.Toolkit.KryptonButton();
        this.navAudit = new Krypton.Toolkit.KryptonButton();
        this.navAnalytics = new Krypton.Toolkit.KryptonButton();
        this.navUsers = new Krypton.Toolkit.KryptonButton();
        this.navSettings = new Krypton.Toolkit.KryptonButton();
        SetupNavButton(this.navDashboard, "navDashboard", "Dashboard", 124);
        SetupNavButton(this.navSync, "navSync", "Sync", 162);
        SetupNavButton(this.navBackup, "navBackup", "Backup", 200);
        SetupNavButton(this.navTrash, "navTrash", "Trash", 238);
        SetupNavButton(this.navServers, "navServers", "Servers", 276);
        SetupNavButton(this.navAudit, "navAudit", "Audit", 314);
        SetupNavButton(this.navAnalytics, "navAnalytics", "Analytics", 352);
        SetupNavButton(this.navUsers, "navUsers", "Users", 390);
        SetupNavButton(this.navSettings, "navSettings", "Settings", 428);
        this.navDashboard.Click += new System.EventHandler(this.navDashboard_Click);
        this.navSync.Click += new System.EventHandler(this.navSync_Click);
        this.navBackup.Click += new System.EventHandler(this.navBackup_Click);
        this.navTrash.Click += new System.EventHandler(this.navTrash_Click);
        this.navServers.Click += new System.EventHandler(this.navServers_Click);
        this.navAudit.Click += new System.EventHandler(this.navAudit_Click);
        this.navAnalytics.Click += new System.EventHandler(this.navAnalytics_Click);
        this.navUsers.Click += new System.EventHandler(this.navUsers_Click);
        this.navSettings.Click += new System.EventHandler(this.navSettings_Click);

        this.lblTreeCap = new Krypton.Toolkit.KryptonLabel();
        this.lblTreeCap.AutoSize = true;
        this.lblTreeCap.Location = new System.Drawing.Point(12, 470);
        this.lblTreeCap.Name = "lblTreeCap";
        this.lblTreeCap.Text = "Files";

        this.treeFiles = new Krypton.Toolkit.KryptonTreeView();
        this.treeFiles.Location = new System.Drawing.Point(12, 494);
        this.treeFiles.Name = "treeFiles";
        this.treeFiles.Size = new System.Drawing.Size(216, 112);
        this.treeFiles.TabIndex = 2;
        this.treeFiles.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.treeFiles_AfterSelect);
        this.treeFiles.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.treeFiles_DoubleClick);

        this.sideStrip = new Krypton.Toolkit.KryptonPanel();
        this.sideStrip.Controls.Add(this.btnExpand);
        this.sideStrip.Dock = System.Windows.Forms.DockStyle.Left;
        this.sideStrip.Location = new System.Drawing.Point(0, 0);
        this.sideStrip.Name = "sideStrip";
        this.sideStrip.Size = new System.Drawing.Size(40, 640);
        this.sideStrip.TabIndex = 5;
        this.sideStrip.Visible = false;

        this.btnExpand = new Krypton.Toolkit.KryptonButton();
        this.btnExpand.AutoSize = false;
        this.btnExpand.Location = new System.Drawing.Point(4, 72);
        this.btnExpand.Name = "btnExpand";
        this.btnExpand.Size = new System.Drawing.Size(32, 36);
        this.btnExpand.TabIndex = 0;
        this.btnExpand.Text = "»";
        this.btnExpand.ButtonStyle = Krypton.Toolkit.ButtonStyle.ListItem;
        this.btnExpand.Click += new System.EventHandler(this.btnExpand_Click);

        this.topSpacer.Dock = System.Windows.Forms.DockStyle.Top;
        this.topSpacer.Location = new System.Drawing.Point(0, 0);
        this.topSpacer.Name = "topSpacer";
        this.topSpacer.Size = new System.Drawing.Size(1210, 64);
        this.topSpacer.TabIndex = 3;

        this.tabControl.Dock = System.Windows.Forms.DockStyle.Fill;
        this.tabControl.Location = new System.Drawing.Point(0, 0);
        this.tabControl.Name = "tabControl";
        this.tabControl.SelectedIndex = 0;
        this.tabControl.Size = new System.Drawing.Size(1210, 640);
        this.tabControl.TabIndex = 0;
        this.tabControl.Controls.Add(this.tabDashboard);
        this.tabControl.Controls.Add(this.tabSync);
        this.tabControl.Controls.Add(this.tabBackup);
        this.tabControl.Controls.Add(this.tabTrash);
        this.tabControl.Controls.Add(this.tabServers);
        this.tabControl.Controls.Add(this.tabAudit);
        this.tabControl.Controls.Add(this.tabAnalytics);
        this.tabControl.Controls.Add(this.tabUsers);
        this.tabControl.Controls.Add(this.tabSettings);

        this.tabDashboard.Controls.Add(this.lblDashTitle);
        this.tabDashboard.Controls.Add(this.cardFiles);
        this.tabDashboard.Controls.Add(this.cardSynced);
        this.tabDashboard.Controls.Add(this.cardPending);
        this.tabDashboard.Controls.Add(this.cardServers);
        this.tabDashboard.Location = new System.Drawing.Point(4, 34);
        this.tabDashboard.Name = "tabDashboard";
        this.tabDashboard.Padding = new System.Windows.Forms.Padding(3);
        this.tabDashboard.Size = new System.Drawing.Size(972, 582);
        this.tabDashboard.TabIndex = 0;
        this.tabDashboard.Text = "Dashboard";

        this.lblDashTitle.AutoSize = true;
        this.lblDashTitle.Location = new System.Drawing.Point(25, 20);
        this.lblDashTitle.Name = "lblDashTitle";
        this.lblDashTitle.Text = "Overview";

        ((System.ComponentModel.ISupportInitialize)(this.picUserAvatar)).BeginInit();
        this.picUserAvatar.Location = new System.Drawing.Point(905, 15);
        this.picUserAvatar.Name = "picUserAvatar";
        this.picUserAvatar.Size = new System.Drawing.Size(48, 48);
        this.picUserAvatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
        this.picUserAvatar.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
        this.picUserAvatar.TabIndex = 10;
        this.picUserAvatar.TabStop = false;
        ((System.ComponentModel.ISupportInitialize)(this.picUserAvatar)).EndInit();

        this.lblUserBadge.AutoSize = false;
        this.lblUserBadge.Location = new System.Drawing.Point(700, 22);
        this.lblUserBadge.Name = "lblUserBadge";
        this.lblUserBadge.Size = new System.Drawing.Size(195, 45);
        this.lblUserBadge.Text = "";
        this.tabDashboard.Controls.Add(this.picUserAvatar);
        this.tabDashboard.Controls.Add(this.lblUserBadge);

        this.lblFilesCap = new Krypton.Toolkit.KryptonLabel();
        this.lblFilesVal = new System.Windows.Forms.Label();
        this.lblSyncedCap = new Krypton.Toolkit.KryptonLabel();
        this.lblSyncedVal = new System.Windows.Forms.Label();
        this.lblPendingCap = new Krypton.Toolkit.KryptonLabel();
        this.lblPendingVal = new System.Windows.Forms.Label();
        this.lblServersCap = new Krypton.Toolkit.KryptonLabel();
        this.lblServersVal = new System.Windows.Forms.Label();

        this.cardFiles.Location = new System.Drawing.Point(25, 70);
        this.cardFiles.Name = "cardFiles";
        this.cardFiles.Size = new System.Drawing.Size(220, 110);
        this.cardFiles.TabIndex = 1;
        this.lblFilesCap.AutoSize = true;
        this.lblFilesCap.Location = new System.Drawing.Point(15, 15);
        this.lblFilesCap.Name = "lblFilesCap";
        this.lblFilesCap.Text = "All files";
        this.lblFilesVal.AutoSize = true;
        this.lblFilesVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblFilesVal.ForeColor = System.Drawing.Color.FromArgb(0, 90, 158);
        this.lblFilesVal.Location = new System.Drawing.Point(15, 50);
        this.lblFilesVal.Name = "lblFilesVal";
        this.lblFilesVal.Text = "0";
        this.cardFiles.Controls.Add(this.lblFilesCap);
        this.cardFiles.Controls.Add(this.lblFilesVal);

        this.cardSynced.Location = new System.Drawing.Point(268, 70);
        this.cardSynced.Name = "cardSynced";
        this.cardSynced.Size = new System.Drawing.Size(220, 110);
        this.cardSynced.TabIndex = 2;
        this.lblSyncedCap.AutoSize = true;
        this.lblSyncedCap.Location = new System.Drawing.Point(15, 15);
        this.lblSyncedCap.Name = "lblSyncedCap";
        this.lblSyncedCap.Text = "Synced";
        this.lblSyncedVal.AutoSize = true;
        this.lblSyncedVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblSyncedVal.ForeColor = System.Drawing.Color.FromArgb(76, 175, 80);
        this.lblSyncedVal.Location = new System.Drawing.Point(15, 50);
        this.lblSyncedVal.Name = "lblSyncedVal";
        this.lblSyncedVal.Text = "0";
        this.cardSynced.Controls.Add(this.lblSyncedCap);
        this.cardSynced.Controls.Add(this.lblSyncedVal);

        this.cardPending.Location = new System.Drawing.Point(511, 70);
        this.cardPending.Name = "cardPending";
        this.cardPending.Size = new System.Drawing.Size(220, 110);
        this.cardPending.TabIndex = 3;
        this.lblPendingCap.AutoSize = true;
        this.lblPendingCap.Location = new System.Drawing.Point(15, 15);
        this.lblPendingCap.Name = "lblPendingCap";
        this.lblPendingCap.Text = "Pending";
        this.lblPendingVal.AutoSize = true;
        this.lblPendingVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblPendingVal.ForeColor = System.Drawing.Color.FromArgb(255, 193, 7);
        this.lblPendingVal.Location = new System.Drawing.Point(15, 50);
        this.lblPendingVal.Name = "lblPendingVal";
        this.lblPendingVal.Text = "0";
        this.cardPending.Controls.Add(this.lblPendingCap);
        this.cardPending.Controls.Add(this.lblPendingVal);

        this.cardServers.Location = new System.Drawing.Point(754, 70);
        this.cardServers.Name = "cardServers";
        this.cardServers.Size = new System.Drawing.Size(220, 110);
        this.cardServers.TabIndex = 4;
        this.lblServersCap.AutoSize = true;
        this.lblServersCap.Location = new System.Drawing.Point(15, 15);
        this.lblServersCap.Name = "lblServersCap";
        this.lblServersCap.Text = "Servers";
        this.lblServersVal.AutoSize = true;
        this.lblServersVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblServersVal.ForeColor = System.Drawing.Color.FromArgb(0, 90, 158);
        this.lblServersVal.Location = new System.Drawing.Point(15, 50);
        this.lblServersVal.Name = "lblServersVal";
        this.lblServersVal.Text = "0";
        this.cardServers.Controls.Add(this.lblServersCap);
        this.cardServers.Controls.Add(this.lblServersVal);

        this.tabSync.Controls.Add(this.gridFiles);
        this.tabSync.Controls.Add(this.lblStatus);
        this.tabSync.Controls.Add(this.btnSelectFolder);
        this.tabSync.Controls.Add(this.btnSync);
        this.tabSync.Controls.Add(this.btnDelete);
        this.tabSync.Controls.Add(this.btnResume);
        this.tabSync.Controls.Add(this.btnExplorer);
        this.tabSync.Controls.Add(this.btnLogout);
        this.tabSync.Location = new System.Drawing.Point(4, 34);
        this.tabSync.Name = "tabSync";
        this.tabSync.Padding = new System.Windows.Forms.Padding(3);
        this.tabSync.Size = new System.Drawing.Size(972, 582);
        this.tabSync.TabIndex = 0;
        this.tabSync.Text = "Sync";

        this.btnSelectFolder.AutoSize = false;
        this.btnSelectFolder.Location = new System.Drawing.Point(15, 15);
        this.btnSelectFolder.Name = "btnSelectFolder";
        this.btnSelectFolder.Size = new System.Drawing.Size(150, 36);
        this.btnSelectFolder.TabIndex = 0;
        this.btnSelectFolder.Text = "Select Folder";
        this.btnSelectFolder.ButtonStyle = Krypton.Toolkit.ButtonStyle.Standalone;
        this.btnSelectFolder.AccessibleName = "Select folder to scan";

        this.lblStatus.AutoSize = true;
        this.lblStatus.Location = new System.Drawing.Point(510, 62);
        this.lblStatus.Name = "lblStatus";
        this.lblStatus.TabIndex = 1;
        this.lblStatus.Text = "Ready.";

        this.btnSync.AutoSize = false;
        this.btnSync.Location = new System.Drawing.Point(180, 15);
        this.btnSync.Name = "btnSync";
        this.btnSync.Size = new System.Drawing.Size(110, 36);
        this.btnSync.TabIndex = 3;
        this.btnSync.Text = "Sync";
        this.btnSync.ButtonStyle = Krypton.Toolkit.ButtonStyle.Standalone;
        this.btnSync.AccessibleName = "Synchronize pending files";

        this.btnDelete.AutoSize = false;
        this.btnDelete.Location = new System.Drawing.Point(305, 15);
        this.btnDelete.Name = "btnDelete";
        this.btnDelete.Size = new System.Drawing.Size(110, 36);
        this.btnDelete.TabIndex = 4;
        this.btnDelete.Text = "Delete";
        this.btnDelete.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.btnDelete.AccessibleName = "Delete selected file";

        this.btnResume.AutoSize = false;
        this.btnResume.Location = new System.Drawing.Point(430, 15);
        this.btnResume.Name = "btnResume";
        this.btnResume.Size = new System.Drawing.Size(110, 36);
        this.btnResume.TabIndex = 5;
        this.btnResume.Text = "Resume";
        this.btnResume.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.btnResume.AccessibleName = "Resume failed uploads";

        this.btnExplorer.AutoSize = false;
        this.btnExplorer.Location = new System.Drawing.Point(555, 15);
        this.btnExplorer.Name = "btnExplorer";
        this.btnExplorer.Size = new System.Drawing.Size(110, 36);
        this.btnExplorer.TabIndex = 9;
        this.btnExplorer.Text = "Explorer";
        this.btnExplorer.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.btnExplorer.AccessibleName = "Open file explorer";

        this.btnLogout.AutoSize = false;
        this.btnLogout.Location = new System.Drawing.Point(850, 15);
        this.btnLogout.Name = "btnLogout";
        this.btnLogout.Size = new System.Drawing.Size(110, 36);
        this.btnLogout.TabIndex = 6;
        this.btnLogout.Text = "Logout";
        this.btnLogout.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.btnLogout.AccessibleName = "Log out";

        this.notifyIcon.Icon = System.Drawing.SystemIcons.Application;
        this.notifyIcon.Text = "DataSyncEngine";
        this.notifyIcon.Visible = true;

        this.trayMenu = new System.Windows.Forms.ContextMenuStrip();
        this.trayShow = new System.Windows.Forms.ToolStripMenuItem();
        this.trayExit = new System.Windows.Forms.ToolStripMenuItem();
        this.trayMenu.Items.Add(this.trayShow);
        this.trayMenu.Items.Add(this.trayExit);
        this.trayShow.Text = "Show";
        this.trayExit.Text = "Exit";
        this.trayShow.Click += new System.EventHandler(this.trayShow_Click);
        this.trayExit.Click += new System.EventHandler(this.trayExit_Click);
        this.trayAbout = new System.Windows.Forms.ToolStripMenuItem();
        this.trayAbout.Text = "About";
        this.trayAbout.Click += new System.EventHandler(this.trayAbout_Click);
        this.trayMenu.Items.Add(this.trayAbout);
        this.trayChangePassword = new System.Windows.Forms.ToolStripMenuItem();
        this.trayChangePassword.Text = "Change Password";
        this.trayChangePassword.Click += new System.EventHandler(this.trayChangePassword_Click);
        this.trayMenu.Items.Add(this.trayChangePassword);
        this.trayLock = new System.Windows.Forms.ToolStripMenuItem();
        this.trayLock.Text = "Lock Screen";
        this.trayLock.Click += new System.EventHandler(this.trayLock_Click);
        this.trayMenu.Items.Add(this.trayLock);
        this.notifyIcon.ContextMenuStrip = this.trayMenu;
        this.notifyIcon.DoubleClick += new System.EventHandler(this.trayShow_Click);

        this.statusStrip = new Krypton.Toolkit.KryptonStatusStrip();
        this.lblServerInfo = new System.Windows.Forms.ToolStripStatusLabel();
        this.statusStrip.Items.Add(this.lblServerInfo);
        this.statusStrip.Location = new System.Drawing.Point(0, 618);
        this.statusStrip.Name = "statusStrip";
        this.statusStrip.Size = new System.Drawing.Size(1210, 22);
        this.statusStrip.TabIndex = 1;
        this.lblServerInfo.Name = "lblServerInfo";
        this.lblServerInfo.Text = "";

        this.btnTheme = new System.Windows.Forms.ToolStripDropDownButton();
        this.themeDarkItem = new System.Windows.Forms.ToolStripMenuItem();
        this.themeLightItem = new System.Windows.Forms.ToolStripMenuItem();
        this.btnTheme.Text = "Theme";
        this.themeDarkItem.Text = "Dark";
        this.themeLightItem.Text = "Light";
        this.btnTheme.DropDownItems.Add(this.themeDarkItem);
        this.btnTheme.DropDownItems.Add(this.themeLightItem);
        this.themeDarkItem.Click += new System.EventHandler(this.themeDarkItem_Click);
        this.themeLightItem.Click += new System.EventHandler(this.themeLightItem_Click);
        this.statusStrip.Items.Add(new System.Windows.Forms.ToolStripSeparator());
        this.statusStrip.Items.Add(this.btnTheme);

        this.btnNotifications = new System.Windows.Forms.ToolStripDropDownButton();
        this.btnNotifications.Name = "btnNotifications";
        this.btnNotifications.Text = "Notifications";
        this.btnNotifications.ToolTipText = "Recent notifications";
        this.statusStrip.Items.Add(this.btnNotifications);

        this.txtFilter = new Krypton.Toolkit.KryptonTextBox();
        this.txtFilter.CueHint.CueHintText = "Type to filter files...";
        this.txtFilter.Location = new System.Drawing.Point(15, 58);
        this.txtFilter.MaxLength = 32767;
        this.txtFilter.Name = "txtFilter";
        this.txtFilter.Size = new System.Drawing.Size(250, 36);
        this.txtFilter.TabIndex = 7;
        this.txtFilter.AccessibleName = "Filter files";
        this.txtFilter.TextChanged += new System.EventHandler(this.txtFilter_TextChanged);
        this.tabSync.Controls.Add(this.txtFilter);

        this.progressBar = new Krypton.Toolkit.KryptonProgressBar();
        this.progressBar.Location = new System.Drawing.Point(280, 61);
        this.progressBar.Name = "progressBar";
        this.progressBar.Size = new System.Drawing.Size(210, 20);
        this.progressBar.TabIndex = 8;
        this.tabSync.Controls.Add(this.progressBar);

        this.gridFiles.Location = new System.Drawing.Point(15, 95);
        this.gridFiles.Size = new System.Drawing.Size(940, 465);

        this.Controls.Add(this.statusStrip);

        this.gridFiles.AllowUserToAddRows = false;
        this.gridFiles.AllowUserToDeleteRows = false;
        this.gridFiles.ReadOnly = true;
        this.gridFiles.Name = "gridFiles";
        this.gridFiles.TabIndex = 2;

        this.tabBackup.Location = new System.Drawing.Point(4, 34);
        this.tabBackup.Name = "tabBackup";
        this.tabBackup.Padding = new System.Windows.Forms.Padding(3);
        this.tabBackup.Size = new System.Drawing.Size(972, 582);
        this.tabBackup.TabIndex = 5;
        this.tabBackup.Text = "Backup";

        this.lblBackupTitle = new Krypton.Toolkit.KryptonLabel();
        this.lblBackupTitle.AutoSize = true;
        this.lblBackupTitle.Location = new System.Drawing.Point(20, 20);
        this.lblBackupTitle.Name = "lblBackupTitle";
        this.lblBackupTitle.Text = "Server backup (export decrypted files)";
        this.tabBackup.Controls.Add(this.lblBackupTitle);

        this.btnBackupNow = new Krypton.Toolkit.KryptonButton();
        this.btnBackupNow.AutoSize = false;
        this.btnBackupNow.Location = new System.Drawing.Point(20, 60);
        this.btnBackupNow.Name = "btnBackupNow";
        this.btnBackupNow.Size = new System.Drawing.Size(220, 36);
        this.btnBackupNow.TabIndex = 0;
        this.btnBackupNow.Text = "Backup Now";
        this.btnBackupNow.ButtonStyle = Krypton.Toolkit.ButtonStyle.Standalone;
        this.btnBackupNow.AccessibleName = "Export all server files to a folder";
        this.btnBackupNow.Click += new System.EventHandler(this.btnBackupNow_Click);
        this.tabBackup.Controls.Add(this.btnBackupNow);

        this.lblBackupInfo = new Krypton.Toolkit.KryptonLabel();
        this.lblBackupInfo.AutoSize = true;
        this.lblBackupInfo.Location = new System.Drawing.Point(20, 115);
        this.lblBackupInfo.Name = "lblBackupInfo";
        this.lblBackupInfo.Text = "No backup yet.";
        this.tabBackup.Controls.Add(this.lblBackupInfo);

        this.lblLastBackup = new Krypton.Toolkit.KryptonLabel();
        this.lblLastBackup.AutoSize = true;
        this.lblLastBackup.Location = new System.Drawing.Point(20, 150);
        this.lblLastBackup.Name = "lblLastBackup";
        this.lblLastBackup.Text = "";
        this.tabBackup.Controls.Add(this.lblLastBackup);

        this.tabTrash.Location = new System.Drawing.Point(4, 34);
        this.tabTrash.Name = "tabTrash";
        this.tabTrash.Padding = new System.Windows.Forms.Padding(3);
        this.tabTrash.Size = new System.Drawing.Size(972, 582);
        this.tabTrash.TabIndex = 6;
        this.tabTrash.Text = "Trash";

        this.btnRestore = new Krypton.Toolkit.KryptonButton();
        this.btnRestore.AutoSize = false;
        this.btnRestore.Location = new System.Drawing.Point(15, 15);
        this.btnRestore.Name = "btnRestore";
        this.btnRestore.Size = new System.Drawing.Size(140, 36);
        this.btnRestore.TabIndex = 0;
        this.btnRestore.Text = "Restore";
        this.btnRestore.ButtonStyle = Krypton.Toolkit.ButtonStyle.Standalone;
        this.btnRestore.AccessibleName = "Restore selected deleted file";
        this.btnRestore.Click += new System.EventHandler(this.btnRestore_Click);
        this.tabTrash.Controls.Add(this.btnRestore);

        this.btnPurge = new Krypton.Toolkit.KryptonButton();
        this.btnPurge.AutoSize = false;
        this.btnPurge.Location = new System.Drawing.Point(170, 15);
        this.btnPurge.Name = "btnPurge";
        this.btnPurge.Size = new System.Drawing.Size(140, 36);
        this.btnPurge.TabIndex = 1;
        this.btnPurge.Text = "Delete Forever";
        this.btnPurge.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.btnPurge.AccessibleName = "Permanently delete selected file";
        this.btnPurge.Click += new System.EventHandler(this.btnPurge_Click);
        this.tabTrash.Controls.Add(this.btnPurge);

        this.lblTrashInfo = new Krypton.Toolkit.KryptonLabel();
        this.lblTrashInfo.AutoSize = true;
        this.lblTrashInfo.Location = new System.Drawing.Point(330, 24);
        this.lblTrashInfo.Name = "lblTrashInfo";
        this.lblTrashInfo.Text = "Deleted files can be restored here.";
        this.tabTrash.Controls.Add(this.lblTrashInfo);

        this.gridTrash = new Krypton.Toolkit.KryptonDataGridView();
        ((System.ComponentModel.ISupportInitialize)(this.gridTrash)).BeginInit();
        this.gridTrash.AllowUserToAddRows = false;
        this.gridTrash.AllowUserToDeleteRows = false;
        this.gridTrash.ReadOnly = true;
        this.gridTrash.Location = new System.Drawing.Point(15, 60);
        this.gridTrash.Name = "gridTrash";
        this.gridTrash.Size = new System.Drawing.Size(940, 500);
        this.gridTrash.TabIndex = 2;
        this.tabTrash.Controls.Add(this.gridTrash);

        this.tabServers.Controls.Add(this.gridServers);
        this.tabServers.Controls.Add(this.btnAddServer);
        this.tabServers.Location = new System.Drawing.Point(4, 34);
        this.tabServers.Name = "tabServers";
        this.tabServers.Size = new System.Drawing.Size(972, 582);
        this.tabServers.TabIndex = 1;
        this.tabServers.Text = "Servers";

        this.btnAddServer.AutoSize = false;
        this.btnAddServer.Location = new System.Drawing.Point(15, 15);
        this.btnAddServer.Name = "btnAddServer";
        this.btnAddServer.Size = new System.Drawing.Size(150, 36);
        this.btnAddServer.TabIndex = 0;
        this.btnAddServer.Text = "Add Server";
        this.btnAddServer.ButtonStyle = Krypton.Toolkit.ButtonStyle.Standalone;

        this.btnEditServer.AutoSize = false;
        this.btnEditServer.Location = new System.Drawing.Point(180, 15);
        this.btnEditServer.Name = "btnEditServer";
        this.btnEditServer.Size = new System.Drawing.Size(140, 36);
        this.btnEditServer.TabIndex = 2;
        this.btnEditServer.Text = "Edit Server";
        this.btnEditServer.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;

        this.btnSetActive.AutoSize = false;
        this.btnSetActive.Location = new System.Drawing.Point(335, 15);
        this.btnSetActive.Name = "btnSetActive";
        this.btnSetActive.Size = new System.Drawing.Size(140, 36);
        this.btnSetActive.TabIndex = 3;
        this.btnSetActive.Text = "Set Active";
        this.btnSetActive.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;

        this.btnDeleteServer.AutoSize = false;
        this.btnDeleteServer.Location = new System.Drawing.Point(490, 15);
        this.btnDeleteServer.Name = "btnDeleteServer";
        this.btnDeleteServer.Size = new System.Drawing.Size(140, 36);
        this.btnDeleteServer.TabIndex = 4;
        this.btnDeleteServer.Text = "Delete Server";
        this.btnDeleteServer.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;

        this.tabServers.Controls.Add(this.btnEditServer);
        this.tabServers.Controls.Add(this.btnSetActive);
        this.tabServers.Controls.Add(this.btnDeleteServer);

        this.gridServers.AllowUserToAddRows = false;
        this.gridServers.AllowUserToDeleteRows = false;
        this.gridServers.ReadOnly = true;
        this.gridServers.Location = new System.Drawing.Point(15, 60);
        this.gridServers.Name = "gridServers";
        this.gridServers.Size = new System.Drawing.Size(940, 500);
        this.gridServers.TabIndex = 1;

        this.tabAudit.Controls.Add(this.gridAudit);
        this.tabAudit.Controls.Add(this.txtAuditFilter);
        this.tabAudit.Controls.Add(this.btnExportAudit);
        this.tabAudit.Location = new System.Drawing.Point(4, 34);
        this.tabAudit.Name = "tabAudit";
        this.tabAudit.Size = new System.Drawing.Size(972, 582);
        this.tabAudit.TabIndex = 2;
        this.tabAudit.Text = "Audit";

        this.txtAuditFilter.CueHint.CueHintText = "Filter audit entries...";
        this.txtAuditFilter.Location = new System.Drawing.Point(15, 15);
        this.txtAuditFilter.MaxLength = 32767;
        this.txtAuditFilter.Name = "txtAuditFilter";
        this.txtAuditFilter.Size = new System.Drawing.Size(320, 36);
        this.txtAuditFilter.TabIndex = 1;
        this.txtAuditFilter.TextChanged += new System.EventHandler(this.txtAuditFilter_TextChanged);

        this.btnExportAudit.Location = new System.Drawing.Point(350, 15);
        this.btnExportAudit.Name = "btnExportAudit";
        this.btnExportAudit.Size = new System.Drawing.Size(160, 36);
        this.btnExportAudit.TabIndex = 2;
        this.btnExportAudit.Text = "Export CSV";
        this.btnExportAudit.ButtonStyle = Krypton.Toolkit.ButtonStyle.Standalone;
        this.btnExportAudit.Click += new System.EventHandler(this.btnExportAudit_Click);

        this.gridAudit.AllowUserToAddRows = false;
        this.gridAudit.AllowUserToDeleteRows = false;
        this.gridAudit.ReadOnly = true;
        this.gridAudit.Location = new System.Drawing.Point(15, 60);
        this.gridAudit.Name = "gridAudit";
        this.gridAudit.Size = new System.Drawing.Size(940, 500);
        this.gridAudit.TabIndex = 0;

        this.tabAnalytics.Controls.Add(this.lblAnalytics);
        this.tabAnalytics.Location = new System.Drawing.Point(4, 34);
        this.tabAnalytics.Name = "tabAnalytics";
        this.tabAnalytics.Size = new System.Drawing.Size(972, 582);
        this.tabAnalytics.TabIndex = 3;
        this.tabAnalytics.Text = "Analytics";

        this.lblAnalytics = new Krypton.Toolkit.KryptonLabel();
        this.lblAnalytics.AutoSize = true;
        this.lblAnalytics.Location = new System.Drawing.Point(20, 20);
        this.lblAnalytics.Name = "lblAnalytics";
        this.lblAnalytics.Text = "Analytics dashboard (Admin only).";

        this.lblAnaTotal = new Krypton.Toolkit.KryptonLabel();
        this.lblAnaSynced = new Krypton.Toolkit.KryptonLabel();
        this.lblAnaPending = new Krypton.Toolkit.KryptonLabel();
        this.lblAnaModified = new Krypton.Toolkit.KryptonLabel();
        this.lblAnaBytes = new Krypton.Toolkit.KryptonLabel();
        this.lblAnaTotal.AutoSize = true;
        this.lblAnaTotal.Location = new System.Drawing.Point(20, 60);
        this.lblAnaTotal.Name = "lblAnaTotal";
        this.lblAnaTotal.Text = "Total files: 0";
        this.lblAnaSynced.AutoSize = true;
        this.lblAnaSynced.Location = new System.Drawing.Point(20, 90);
        this.lblAnaSynced.Name = "lblAnaSynced";
        this.lblAnaSynced.Text = "Synced: 0";
        this.lblAnaPending.AutoSize = true;
        this.lblAnaPending.Location = new System.Drawing.Point(20, 120);
        this.lblAnaPending.Name = "lblAnaPending";
        this.lblAnaPending.Text = "Pending: 0";
        this.lblAnaModified.AutoSize = true;
        this.lblAnaModified.Location = new System.Drawing.Point(20, 150);
        this.lblAnaModified.Name = "lblAnaModified";
        this.lblAnaModified.Text = "Modified: 0";
        this.lblAnaBytes.AutoSize = true;
        this.lblAnaBytes.Location = new System.Drawing.Point(20, 180);
        this.lblAnaBytes.Name = "lblAnaBytes";
        this.lblAnaBytes.Text = "Total size: 0 bytes";
        this.tabAnalytics.Controls.Add(this.lblAnaTotal);
        this.tabAnalytics.Controls.Add(this.lblAnaSynced);
        this.tabAnalytics.Controls.Add(this.lblAnaPending);
        this.tabAnalytics.Controls.Add(this.lblAnaModified);
        this.tabAnalytics.Controls.Add(this.lblAnaBytes);

        this.tabSettings.Location = new System.Drawing.Point(4, 34);
        this.tabSettings.Name = "tabSettings";
        this.tabSettings.Padding = new System.Windows.Forms.Padding(3);
        this.tabSettings.Size = new System.Drawing.Size(972, 582);
        this.tabSettings.TabIndex = 7;
        this.tabSettings.Text = "Settings";

        this.lblSetTheme = new Krypton.Toolkit.KryptonLabel();
        this.lblSetTheme.AutoSize = true;
        this.lblSetTheme.Location = new System.Drawing.Point(20, 20);
        this.lblSetTheme.Name = "lblSetTheme";
        this.lblSetTheme.Text = "Theme";
        this.tabSettings.Controls.Add(this.lblSetTheme);

        this.radDark = new Krypton.Toolkit.KryptonRadioButton();
        this.radDark.AutoSize = true;
        this.radDark.Location = new System.Drawing.Point(20, 50);
        this.radDark.Name = "radDark";
        this.radDark.Size = new System.Drawing.Size(80, 37);
        this.radDark.TabIndex = 0;
        this.radDark.Text = "Dark";
        this.radDark.CheckedChanged += new System.EventHandler(this.radDark_CheckedChanged);
        this.tabSettings.Controls.Add(this.radDark);

        this.radLight = new Krypton.Toolkit.KryptonRadioButton();
        this.radLight.AutoSize = true;
        this.radLight.Location = new System.Drawing.Point(140, 50);
        this.radLight.Name = "radLight";
        this.radLight.Size = new System.Drawing.Size(80, 37);
        this.radLight.TabIndex = 1;
        this.radLight.Text = "Light";
        this.radLight.CheckedChanged += new System.EventHandler(this.radLight_CheckedChanged);
        this.tabSettings.Controls.Add(this.radLight);

        this.lblSetFont = new Krypton.Toolkit.KryptonLabel();
        this.lblSetFont.AutoSize = true;
        this.lblSetFont.Location = new System.Drawing.Point(20, 105);
        this.lblSetFont.Name = "lblSetFont";
        this.lblSetFont.Text = "Font size";
        this.tabSettings.Controls.Add(this.lblSetFont);

        this.trkFontSize = new Krypton.Toolkit.KryptonTrackBar();
        this.trkFontSize.Location = new System.Drawing.Point(20, 135);
        this.trkFontSize.Minimum = 8;
        this.trkFontSize.Maximum = 16;
        this.trkFontSize.Name = "trkFontSize";
        this.trkFontSize.Size = new System.Drawing.Size(250, 45);
        this.trkFontSize.TabIndex = 2;
        this.trkFontSize.ValueChanged += new System.EventHandler(this.trkFontSize_ValueChanged);
        this.tabSettings.Controls.Add(this.trkFontSize);

        this.lblFontSizeVal = new Krypton.Toolkit.KryptonLabel();
        this.lblFontSizeVal.AutoSize = true;
        this.lblFontSizeVal.Location = new System.Drawing.Point(280, 145);
        this.lblFontSizeVal.Name = "lblFontSizeVal";
        this.lblFontSizeVal.Text = "9.5";
        this.tabSettings.Controls.Add(this.lblFontSizeVal);

        this.lblFontPreview = new Krypton.Toolkit.KryptonLabel();
        this.lblFontPreview.AutoSize = true;
        this.lblFontPreview.Location = new System.Drawing.Point(20, 185);
        this.lblFontPreview.Name = "lblFontPreview";
        this.lblFontPreview.Text = "AaBbCcDd 123";
        this.tabSettings.Controls.Add(this.lblFontPreview);

        this.chkBold = new Krypton.Toolkit.KryptonCheckBox();
        this.chkBold.AutoSize = true;
        this.chkBold.Location = new System.Drawing.Point(20, 220);
        this.chkBold.Name = "chkBold";
        this.chkBold.Size = new System.Drawing.Size(130, 37);
        this.chkBold.TabIndex = 3;
        this.chkBold.Text = "Bold text";
        this.chkBold.CheckedChanged += new System.EventHandler(this.chkBold_CheckedChanged);
        this.tabSettings.Controls.Add(this.chkBold);

        this.lblSetAccent = new Krypton.Toolkit.KryptonLabel();
        this.lblSetAccent.AutoSize = true;
        this.lblSetAccent.Location = new System.Drawing.Point(20, 270);
        this.lblSetAccent.Name = "lblSetAccent";
        this.lblSetAccent.Text = "Accent color";
        this.tabSettings.Controls.Add(this.lblSetAccent);

        this.cmbAccent = new Krypton.Toolkit.KryptonComboBox();
        this.cmbAccent.CueHint.CueHintText = "Accent";
        this.cmbAccent.Location = new System.Drawing.Point(20, 300);
        this.cmbAccent.Name = "cmbAccent";
        this.cmbAccent.Size = new System.Drawing.Size(250, 48);
        this.cmbAccent.TabIndex = 4;
        this.cmbAccent.SelectedIndexChanged += new System.EventHandler(this.cmbAccent_SelectedIndexChanged);
        this.tabSettings.Controls.Add(this.cmbAccent);

        this.swAnimations = new Krypton.Toolkit.KryptonToggleSwitch();
        this.swAnimations.AutoSize = true;
        this.swAnimations.Location = new System.Drawing.Point(480, 50);
        this.swAnimations.Name = "swAnimations";
        this.swAnimations.Size = new System.Drawing.Size(200, 37);
        this.swAnimations.TabIndex = 5;
        this.swAnimations.Text = "Animations";
        this.swAnimations.CheckedChanged += new System.EventHandler(this.swAnimations_CheckedChanged);
        this.tabSettings.Controls.Add(this.swAnimations);

        this.swConfirmDelete = new Krypton.Toolkit.KryptonToggleSwitch();
        this.swConfirmDelete.AutoSize = true;
        this.swConfirmDelete.Location = new System.Drawing.Point(480, 100);
        this.swConfirmDelete.Name = "swConfirmDelete";
        this.swConfirmDelete.Size = new System.Drawing.Size(240, 37);
        this.swConfirmDelete.TabIndex = 6;
        this.swConfirmDelete.Text = "Confirm before delete";
        this.swConfirmDelete.CheckedChanged += new System.EventHandler(this.swConfirmDelete_CheckedChanged);
        this.tabSettings.Controls.Add(this.swConfirmDelete);

        this.swNotifications = new Krypton.Toolkit.KryptonToggleSwitch();
        this.swNotifications.AutoSize = true;
        this.swNotifications.Location = new System.Drawing.Point(480, 150);
        this.swNotifications.Name = "swNotifications";
        this.swNotifications.Size = new System.Drawing.Size(220, 37);
        this.swNotifications.TabIndex = 7;
        this.swNotifications.Text = "Tray notifications";
        this.swNotifications.CheckedChanged += new System.EventHandler(this.swNotifications_CheckedChanged);
        this.tabSettings.Controls.Add(this.swNotifications);

        this.swColdStorage = new Krypton.Toolkit.KryptonToggleSwitch();
        this.swColdStorage.AutoSize = true;
        this.swColdStorage.Location = new System.Drawing.Point(480, 200);
        this.swColdStorage.Name = "swColdStorage";
        this.swColdStorage.Size = new System.Drawing.Size(260, 37);
        this.swColdStorage.TabIndex = 8;
        this.swColdStorage.Text = "Keep local cold copy";
        this.swColdStorage.CheckedChanged += new System.EventHandler(this.swColdStorage_CheckedChanged);
        this.tabSettings.Controls.Add(this.swColdStorage);

        this.swMinimizeToTray = new Krypton.Toolkit.KryptonToggleSwitch();
        this.swMinimizeToTray.AutoSize = true;
        this.swMinimizeToTray.Location = new System.Drawing.Point(480, 250);
        this.swMinimizeToTray.Name = "swMinimizeToTray";
        this.swMinimizeToTray.Size = new System.Drawing.Size(240, 37);
        this.swMinimizeToTray.TabIndex = 9;
        this.swMinimizeToTray.Text = "Minimize to tray";
        this.swMinimizeToTray.CheckedChanged += new System.EventHandler(this.swMinimizeToTray_CheckedChanged);
        this.tabSettings.Controls.Add(this.swMinimizeToTray);

        this.btnResetSettings = new Krypton.Toolkit.KryptonButton();
        this.btnResetSettings.AutoSize = false;
        this.btnResetSettings.Location = new System.Drawing.Point(480, 350);
        this.btnResetSettings.Name = "btnResetSettings";
        this.btnResetSettings.Size = new System.Drawing.Size(200, 36);
        this.btnResetSettings.TabIndex = 10;
        this.btnResetSettings.Text = "Reset Defaults";
        this.btnResetSettings.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.btnResetSettings.Click += new System.EventHandler(this.btnResetSettings_Click);
        this.tabSettings.Controls.Add(this.btnResetSettings);

        this.swAutoSync = new Krypton.Toolkit.KryptonToggleSwitch();
        this.swAutoSync.AutoSize = true;
        this.swAutoSync.Location = new System.Drawing.Point(480, 300);
        this.swAutoSync.Name = "swAutoSync";
        this.swAutoSync.Size = new System.Drawing.Size(200, 37);
        this.swAutoSync.TabIndex = 11;
        this.swAutoSync.Text = "Auto-sync on change";
        this.swAutoSync.CheckedChanged += new System.EventHandler(this.swAutoSync_CheckedChanged);
        this.tabSettings.Controls.Add(this.swAutoSync);

        this.lblSetIdle = new Krypton.Toolkit.KryptonLabel();
        this.lblSetIdle.AutoSize = true;
        this.lblSetIdle.Location = new System.Drawing.Point(480, 400);
        this.lblSetIdle.Name = "lblSetIdle";
        this.lblSetIdle.Text = "Auto-logout when idle (minutes)";
        this.tabSettings.Controls.Add(this.lblSetIdle);

        this.cmbIdle = new Krypton.Toolkit.KryptonComboBox();
        this.cmbIdle.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        this.cmbIdle.Location = new System.Drawing.Point(480, 428);
        this.cmbIdle.Name = "cmbIdle";
        this.cmbIdle.Size = new System.Drawing.Size(250, 48);
        this.cmbIdle.TabIndex = 13;
        this.cmbIdle.SelectedIndexChanged += new System.EventHandler(this.cmbIdle_SelectedIndexChanged);
        this.tabSettings.Controls.Add(this.cmbIdle);

        this.lblSetAutoBackup = new Krypton.Toolkit.KryptonLabel();
        this.lblSetAutoBackup.AutoSize = true;
        this.lblSetAutoBackup.Location = new System.Drawing.Point(480, 484);
        this.lblSetAutoBackup.Name = "lblSetAutoBackup";
        this.lblSetAutoBackup.Text = "Automatic backup (hours, 0 = off)";
        this.tabSettings.Controls.Add(this.lblSetAutoBackup);

        this.cmbAutoBackup = new Krypton.Toolkit.KryptonComboBox();
        this.cmbAutoBackup.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        this.cmbAutoBackup.Location = new System.Drawing.Point(480, 512);
        this.cmbAutoBackup.Name = "cmbAutoBackup";
        this.cmbAutoBackup.Size = new System.Drawing.Size(250, 48);
        this.cmbAutoBackup.TabIndex = 14;
        this.cmbAutoBackup.SelectedIndexChanged += new System.EventHandler(this.cmbAutoBackup_SelectedIndexChanged);
        this.tabSettings.Controls.Add(this.cmbAutoBackup);

        this.lblExcludeCap = new Krypton.Toolkit.KryptonLabel();
        this.lblExcludeCap.AutoSize = true;
        this.lblExcludeCap.Location = new System.Drawing.Point(20, 360);
        this.lblExcludeCap.Name = "lblExcludeCap";
        this.lblExcludeCap.Text = "Exclude patterns (separated by ;)";
        this.tabSettings.Controls.Add(this.lblExcludeCap);

        this.txtExclude = new Krypton.Toolkit.KryptonTextBox();
        this.txtExclude.CueHint.CueHintText = "*.tmp;*.log;~$*";
        this.txtExclude.Location = new System.Drawing.Point(20, 390);
        this.txtExclude.MaxLength = 1024;
        this.txtExclude.Name = "txtExclude";
        this.txtExclude.Size = new System.Drawing.Size(450, 48);
        this.txtExclude.TabIndex = 12;
        this.txtExclude.Leave += new System.EventHandler(this.txtExclude_Leave);
        this.tabSettings.Controls.Add(this.txtExclude);

        this.lblAnaServer = new Krypton.Toolkit.KryptonLabel();
        this.lblAnaServer.AutoSize = true;
        this.lblAnaServer.Location = new System.Drawing.Point(20, 210);
        this.lblAnaServer.Name = "lblAnaServer";
        this.lblAnaServer.Text = "Server files: -";
        this.tabAnalytics.Controls.Add(this.lblAnaServer);

        this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(1210, 640);
        this.Controls.Add(this.tabControl);
        this.Controls.Add(this.topSpacer);
        this.Controls.Add(this.sideBar);
        this.Controls.Add(this.sideStrip);
        this.Name = "MainView";
        this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        this.Text = "DataSyncEngine";
        this.KeyPreview = true;
        this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.MainView_KeyDown);

        this.toolTip = new System.Windows.Forms.ToolTip(this.components);
        this.toolTip.SetToolTip(this.btnSelectFolder, "Choose a folder to scan");
        this.toolTip.SetToolTip(this.btnSync, "Upload pending files (Ctrl+S)");
        this.toolTip.SetToolTip(this.btnDelete, "Delete the selected file (Del)");
        this.toolTip.SetToolTip(this.btnResume, "Resume failed uploads");
        this.toolTip.SetToolTip(this.btnExplorer, "Open the file explorer");
        this.toolTip.SetToolTip(this.btnLogout, "Log out of the application");
        this.toolTip.SetToolTip(this.txtFilter, "Type to filter files (Ctrl+F)");
        this.toolTip.SetToolTip(this.progressBar, "Synchronization progress");
        this.toolTip.SetToolTip(this.btnBackupNow, "Export all server files to a folder");
        this.toolTip.SetToolTip(this.btnRestore, "Restore the selected deleted file");
        this.tabControl.ResumeLayout(false);
        this.tabSync.ResumeLayout(false);
        this.tabSync.PerformLayout();
        this.tabServers.ResumeLayout(false);
        this.tabServers.PerformLayout();
        this.tabAudit.ResumeLayout(false);
        this.tabAnalytics.ResumeLayout(false);
        this.tabAnalytics.PerformLayout();

        this.tabUsers.SuspendLayout();
        this.tabUsers.Controls.Add(this.gridUsers);
        this.tabUsers.Controls.Add(this.btnAddUser);
        this.tabUsers.Controls.Add(this.btnDeleteUser);
        this.tabUsers.Location = new System.Drawing.Point(4, 34);
        this.tabUsers.Name = "tabUsers";
        this.tabUsers.Size = new System.Drawing.Size(972, 582);
        this.tabUsers.TabIndex = 4;
        this.tabUsers.Text = "Users";

        this.btnAddUser.AutoSize = false;
        this.btnAddUser.Location = new System.Drawing.Point(15, 15);
        this.btnAddUser.Name = "btnAddUser";
        this.btnAddUser.Size = new System.Drawing.Size(140, 36);
        this.btnAddUser.TabIndex = 0;
        this.btnAddUser.Text = "Add User";
        this.btnAddUser.ButtonStyle = Krypton.Toolkit.ButtonStyle.Standalone;

        this.btnDeleteUser.AutoSize = false;
        this.btnDeleteUser.Location = new System.Drawing.Point(170, 15);
        this.btnDeleteUser.Name = "btnDeleteUser";
        this.btnDeleteUser.Size = new System.Drawing.Size(140, 36);
        this.btnDeleteUser.TabIndex = 1;
        this.btnDeleteUser.Text = "Delete User";
        this.btnDeleteUser.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;

        this.btnViewProfile = new Krypton.Toolkit.KryptonButton();
        this.btnViewProfile.Location = new System.Drawing.Point(325, 15);
        this.btnViewProfile.Name = "btnViewProfile";
        this.btnViewProfile.Size = new System.Drawing.Size(140, 36);
        this.btnViewProfile.TabIndex = 3;
        this.btnViewProfile.Text = "View Profile";
        this.btnViewProfile.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.tabUsers.Controls.Add(this.btnViewProfile);

        this.btnResetPassword = new Krypton.Toolkit.KryptonButton();
        this.btnResetPassword.Location = new System.Drawing.Point(480, 15);
        this.btnResetPassword.Name = "btnResetPassword";
        this.btnResetPassword.Size = new System.Drawing.Size(150, 36);
        this.btnResetPassword.TabIndex = 4;
        this.btnResetPassword.Text = "Reset Password";
        this.btnResetPassword.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.tabUsers.Controls.Add(this.btnResetPassword);

        this.btnExportUsers = new Krypton.Toolkit.KryptonButton();
        this.btnExportUsers.Location = new System.Drawing.Point(645, 15);
        this.btnExportUsers.Name = "btnExportUsers";
        this.btnExportUsers.Size = new System.Drawing.Size(150, 36);
        this.btnExportUsers.TabIndex = 5;
        this.btnExportUsers.Text = "Export CSV";
        this.btnExportUsers.ButtonStyle = Krypton.Toolkit.ButtonStyle.Alternate;
        this.tabUsers.Controls.Add(this.btnExportUsers);

        this.gridUsers.AllowUserToAddRows = false;
        this.gridUsers.AllowUserToDeleteRows = false;
        this.gridUsers.ReadOnly = true;
        this.gridUsers.Location = new System.Drawing.Point(15, 60);
        this.gridUsers.Name = "gridUsers";
        this.gridUsers.Size = new System.Drawing.Size(940, 500);
        this.gridUsers.TabIndex = 2;
        this.tabUsers.ResumeLayout(false);

        ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridFiles)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridServers)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridAudit)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridTrash)).EndInit();
        this.tabBackup.ResumeLayout(false);
        this.tabTrash.ResumeLayout(false);
        this.tabTrash.PerformLayout();
        this.tabSettings.ResumeLayout(false);
        this.tabSettings.PerformLayout();
        this.sideBar.ResumeLayout(false);
        this.sideBar.PerformLayout();
        this.sideStrip.ResumeLayout(false);
        this.ResumeLayout(false);
    }

    private System.Windows.Forms.TabControl tabControl;
    private Krypton.Toolkit.KryptonPanel topSpacer;
    private Krypton.Toolkit.KryptonPanel sideBar;
    private Krypton.Toolkit.KryptonPanel sideStrip;
    private System.Windows.Forms.PictureBox picSideLogo;
    private Krypton.Toolkit.KryptonLabel lblSideTitle;
    private Krypton.Toolkit.KryptonButton btnNavToggle;
    private Krypton.Toolkit.KryptonButton btnExpand;
    private Krypton.Toolkit.KryptonButton navDashboard;
    private Krypton.Toolkit.KryptonButton navSync;
    private Krypton.Toolkit.KryptonButton navBackup;
    private Krypton.Toolkit.KryptonButton navTrash;
    private Krypton.Toolkit.KryptonButton navServers;
    private Krypton.Toolkit.KryptonButton navAudit;
    private Krypton.Toolkit.KryptonButton navAnalytics;
    private Krypton.Toolkit.KryptonButton navUsers;
    private Krypton.Toolkit.KryptonButton navSettings;
    private Krypton.Toolkit.KryptonLabel lblTreeCap;
    private Krypton.Toolkit.KryptonTreeView treeFiles;
    private System.Windows.Forms.TabPage tabDashboard;
    private System.Windows.Forms.TabPage tabSync;
    private System.Windows.Forms.TabPage tabBackup;
    private Krypton.Toolkit.KryptonLabel lblBackupTitle;
    private Krypton.Toolkit.KryptonButton btnBackupNow;
    private Krypton.Toolkit.KryptonLabel lblBackupInfo;
    private Krypton.Toolkit.KryptonLabel lblLastBackup;
    private System.Windows.Forms.TabPage tabTrash;
    private Krypton.Toolkit.KryptonButton btnRestore;
    private Krypton.Toolkit.KryptonButton btnPurge;
    private Krypton.Toolkit.KryptonLabel lblTrashInfo;
    private Krypton.Toolkit.KryptonDataGridView gridTrash;
    private System.Windows.Forms.TabPage tabSettings;
    private Krypton.Toolkit.KryptonLabel lblSetTheme;
    private Krypton.Toolkit.KryptonRadioButton radDark;
    private Krypton.Toolkit.KryptonRadioButton radLight;
    private Krypton.Toolkit.KryptonLabel lblSetFont;
    private Krypton.Toolkit.KryptonTrackBar trkFontSize;
    private Krypton.Toolkit.KryptonLabel lblFontSizeVal;
    private Krypton.Toolkit.KryptonLabel lblFontPreview;
    private Krypton.Toolkit.KryptonCheckBox chkBold;
    private Krypton.Toolkit.KryptonLabel lblSetAccent;
    private Krypton.Toolkit.KryptonComboBox cmbAccent;
    private Krypton.Toolkit.KryptonToggleSwitch swAnimations;
    private Krypton.Toolkit.KryptonToggleSwitch swConfirmDelete;
    private Krypton.Toolkit.KryptonToggleSwitch swNotifications;
    private Krypton.Toolkit.KryptonToggleSwitch swColdStorage;
    private Krypton.Toolkit.KryptonToggleSwitch swMinimizeToTray;
    private Krypton.Toolkit.KryptonToggleSwitch swAutoSync;
    private Krypton.Toolkit.KryptonLabel lblExcludeCap;
    private Krypton.Toolkit.KryptonTextBox txtExclude;
    private Krypton.Toolkit.KryptonLabel lblSetIdle;
    private Krypton.Toolkit.KryptonComboBox cmbIdle;
    private Krypton.Toolkit.KryptonLabel lblSetAutoBackup;
    private Krypton.Toolkit.KryptonComboBox cmbAutoBackup;
    private Krypton.Toolkit.KryptonButton btnResetSettings;
    private Krypton.Toolkit.KryptonPanel cardFiles;
    private Krypton.Toolkit.KryptonLabel lblFilesCap;
    private System.Windows.Forms.Label lblFilesVal;
    private Krypton.Toolkit.KryptonPanel cardSynced;
    private Krypton.Toolkit.KryptonLabel lblSyncedCap;
    private System.Windows.Forms.Label lblSyncedVal;
    private Krypton.Toolkit.KryptonPanel cardPending;
    private Krypton.Toolkit.KryptonLabel lblPendingCap;
    private System.Windows.Forms.Label lblPendingVal;
    private Krypton.Toolkit.KryptonPanel cardServers;
    private Krypton.Toolkit.KryptonLabel lblServersCap;
    private System.Windows.Forms.Label lblServersVal;
    private Krypton.Toolkit.KryptonLabel lblDashTitle;
    private System.Windows.Forms.PictureBox picUserAvatar;
    private Krypton.Toolkit.KryptonLabel lblUserBadge;
    private System.Windows.Forms.TabPage tabServers;
    private System.Windows.Forms.TabPage tabAudit;
    private System.Windows.Forms.TabPage tabAnalytics;
    private Krypton.Toolkit.KryptonButton btnSelectFolder;
    private Krypton.Toolkit.KryptonButton btnSync;
    private Krypton.Toolkit.KryptonButton btnDelete;
    private Krypton.Toolkit.KryptonButton btnResume;
    private Krypton.Toolkit.KryptonButton btnExplorer;
    private Krypton.Toolkit.KryptonButton btnLogout;
    private Krypton.Toolkit.KryptonButton btnAddUser;
    private Krypton.Toolkit.KryptonButton btnDeleteUser;
    private Krypton.Toolkit.KryptonButton btnViewProfile;
    private Krypton.Toolkit.KryptonButton btnResetPassword;
    private Krypton.Toolkit.KryptonButton btnExportUsers;
    private Krypton.Toolkit.KryptonDataGridView gridUsers;
    private System.Windows.Forms.TabPage tabUsers;
    private Krypton.Toolkit.KryptonButton btnEditServer;
    private Krypton.Toolkit.KryptonButton btnSetActive;
    private Krypton.Toolkit.KryptonButton btnDeleteServer;
    private Krypton.Toolkit.KryptonStatusStrip statusStrip;
    private System.Windows.Forms.ToolStripStatusLabel lblServerInfo;
    private System.Windows.Forms.ToolStripDropDownButton btnTheme;
    private System.Windows.Forms.ToolStripDropDownButton btnNotifications;
    private System.Windows.Forms.ToolStripMenuItem themeDarkItem;
    private System.Windows.Forms.ToolStripMenuItem themeLightItem;
    private Krypton.Toolkit.KryptonTextBox txtFilter;
    private Krypton.Toolkit.KryptonProgressBar progressBar;
    private System.Windows.Forms.ToolTip toolTip;
    private System.Windows.Forms.ToolStripMenuItem trayAbout;
    private System.Windows.Forms.ToolStripMenuItem trayChangePassword;
    private System.Windows.Forms.ToolStripMenuItem trayLock;
    private System.Windows.Forms.ContextMenuStrip trayMenu;
    private System.Windows.Forms.ToolStripMenuItem trayShow;
    private System.Windows.Forms.ToolStripMenuItem trayExit;
    private System.Windows.Forms.NotifyIcon notifyIcon;
    private Krypton.Toolkit.KryptonLabel lblStatus;
    private Krypton.Toolkit.KryptonDataGridView gridFiles;
    private Krypton.Toolkit.KryptonButton btnAddServer;
    private Krypton.Toolkit.KryptonDataGridView gridServers;
    private Krypton.Toolkit.KryptonDataGridView gridAudit;
    private Krypton.Toolkit.KryptonTextBox txtAuditFilter;
    private Krypton.Toolkit.KryptonButton btnExportAudit;
    private Krypton.Toolkit.KryptonLabel lblAnalytics;
    private Krypton.Toolkit.KryptonLabel lblAnaTotal;
    private Krypton.Toolkit.KryptonLabel lblAnaSynced;
    private Krypton.Toolkit.KryptonLabel lblAnaPending;
    private Krypton.Toolkit.KryptonLabel lblAnaModified;
    private Krypton.Toolkit.KryptonLabel lblAnaBytes;
    private Krypton.Toolkit.KryptonLabel lblAnaServer;
}
