namespace Views.Forms;

partial class MainView : MaterialSkin.Controls.MaterialForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.tabControl = new MaterialSkin.Controls.MaterialTabControl();
        this.tabSelector = new MaterialSkin.Controls.MaterialTabSelector();
        this.topSpacer = new System.Windows.Forms.Panel();
        this.sideBar = new System.Windows.Forms.Panel();
        this.sideStrip = new System.Windows.Forms.Panel();
        this.cardFiles = new MaterialSkin.Controls.MaterialCard();
        this.cardSynced = new MaterialSkin.Controls.MaterialCard();
        this.cardPending = new MaterialSkin.Controls.MaterialCard();
        this.cardServers = new MaterialSkin.Controls.MaterialCard();
        this.lblDashTitle = new MaterialSkin.Controls.MaterialLabel();
        this.tabDashboard = new System.Windows.Forms.TabPage();
        this.tabSync = new System.Windows.Forms.TabPage();
        this.tabServers = new System.Windows.Forms.TabPage();
        this.tabAudit = new System.Windows.Forms.TabPage();
        this.tabAnalytics = new System.Windows.Forms.TabPage();
        this.tabUsers = new System.Windows.Forms.TabPage();
        this.tabBackup = new System.Windows.Forms.TabPage();
        this.tabTrash = new System.Windows.Forms.TabPage();
        this.tabSettings = new System.Windows.Forms.TabPage();
        this.btnEditServer = new MaterialSkin.Controls.MaterialButton();
        this.btnSetActive = new MaterialSkin.Controls.MaterialButton();
        this.btnDeleteServer = new MaterialSkin.Controls.MaterialButton();
        this.btnAddUser = new MaterialSkin.Controls.MaterialButton();
        this.btnDeleteUser = new MaterialSkin.Controls.MaterialButton();
        this.gridUsers = new System.Windows.Forms.DataGridView();
        this.btnSelectFolder = new MaterialSkin.Controls.MaterialButton();
        this.btnSync = new MaterialSkin.Controls.MaterialButton();
        this.btnDelete = new MaterialSkin.Controls.MaterialButton();
        this.btnResume = new MaterialSkin.Controls.MaterialButton();
        this.btnExplorer = new MaterialSkin.Controls.MaterialButton();
        this.btnLogout = new MaterialSkin.Controls.MaterialButton();
        this.lblStatus = new MaterialSkin.Controls.MaterialLabel();
        this.gridFiles = new System.Windows.Forms.DataGridView();
        this.notifyIcon = new System.Windows.Forms.NotifyIcon();
        this.components = new System.ComponentModel.Container();
        this.btnAddServer = new MaterialSkin.Controls.MaterialButton();
        this.gridServers = new System.Windows.Forms.DataGridView();
        this.gridAudit = new System.Windows.Forms.DataGridView();
        this.lblAnalytics = new MaterialSkin.Controls.MaterialLabel();
        this.tabControl.SuspendLayout();
        this.tabDashboard.SuspendLayout();
        this.tabSync.SuspendLayout();
        this.tabServers.SuspendLayout();
        this.tabAudit.SuspendLayout();
        this.tabAnalytics.SuspendLayout();
        this.tabBackup.SuspendLayout();
        this.tabTrash.SuspendLayout();
        this.tabSettings.SuspendLayout();
        this.sideBar.SuspendLayout();
        this.sideStrip.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)(this.gridFiles)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridServers)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridAudit)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).BeginInit();
        this.sideBar.SuspendLayout();
        this.SuspendLayout();

        this.sideBar.Controls.Add(this.picSideLogo);
        this.sideBar.Controls.Add(this.lblSideTitle);
        this.sideBar.Controls.Add(this.btnNavToggle);
        this.sideBar.Controls.Add(this.navDashboard);
        this.sideBar.Controls.Add(this.navSync);
        this.sideBar.Controls.Add(this.navBackup);
        this.sideBar.Controls.Add(this.navTrash);
        this.sideBar.Controls.Add(this.navServers);
        this.sideBar.Controls.Add(this.navAudit);
        this.sideBar.Controls.Add(this.navAnalytics);
        this.sideBar.Controls.Add(this.navUsers);
        this.sideBar.Controls.Add(this.navSettings);
        this.sideBar.Controls.Add(this.lblTreeCap);
        this.sideBar.Controls.Add(this.treeFiles);
        this.sideBar.Dock = System.Windows.Forms.DockStyle.Left;
        this.sideBar.Location = new System.Drawing.Point(0, 0);
        this.sideBar.Name = "sideBar";
        this.sideBar.Size = new System.Drawing.Size(240, 640);
        this.sideBar.TabIndex = 4;

        this.picSideLogo = new System.Windows.Forms.PictureBox();
        ((System.ComponentModel.ISupportInitialize)(this.picSideLogo)).BeginInit();
        this.picSideLogo.Location = new System.Drawing.Point(12, 70);
        this.picSideLogo.Name = "picSideLogo";
        this.picSideLogo.Size = new System.Drawing.Size(40, 40);
        this.picSideLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
        this.picSideLogo.TabIndex = 0;
        this.picSideLogo.TabStop = false;
        ((System.ComponentModel.ISupportInitialize)(this.picSideLogo)).EndInit();

        this.lblSideTitle = new MaterialSkin.Controls.MaterialLabel();
        this.lblSideTitle.AutoSize = true;
        this.lblSideTitle.Location = new System.Drawing.Point(58, 80);
        this.lblSideTitle.Name = "lblSideTitle";
        this.lblSideTitle.Text = "DataSync";

        this.btnNavToggle = new MaterialSkin.Controls.MaterialButton();
        this.btnNavToggle.AutoSize = false;
        this.btnNavToggle.HighEmphasis = false;
        this.btnNavToggle.Location = new System.Drawing.Point(196, 72);
        this.btnNavToggle.Name = "btnNavToggle";
        this.btnNavToggle.Size = new System.Drawing.Size(32, 36);
        this.btnNavToggle.TabIndex = 1;
        this.btnNavToggle.Text = "«";
        this.btnNavToggle.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Text;
        this.btnNavToggle.UseAccentColor = false;
        this.btnNavToggle.Click += new System.EventHandler(this.btnNavToggle_Click);

        this.navDashboard = new MaterialSkin.Controls.MaterialButton();
        this.navSync = new MaterialSkin.Controls.MaterialButton();
        this.navBackup = new MaterialSkin.Controls.MaterialButton();
        this.navTrash = new MaterialSkin.Controls.MaterialButton();
        this.navServers = new MaterialSkin.Controls.MaterialButton();
        this.navAudit = new MaterialSkin.Controls.MaterialButton();
        this.navAnalytics = new MaterialSkin.Controls.MaterialButton();
        this.navUsers = new MaterialSkin.Controls.MaterialButton();
        this.navSettings = new MaterialSkin.Controls.MaterialButton();
        SetupNavButton(this.navDashboard, "navDashboard", "Dashboard", 124);
        SetupNavButton(this.navSync, "navSync", "Sync", 162);
        SetupNavButton(this.navBackup, "navBackup", "Backup", 200);
        SetupNavButton(this.navTrash, "navTrash", "Trash", 238);
        SetupNavButton(this.navServers, "navServers", "Servers", 276);
        SetupNavButton(this.navAudit, "navAudit", "Audit", 314);
        SetupNavButton(this.navAnalytics, "navAnalytics", "Analytics", 352);
        SetupNavButton(this.navUsers, "navUsers", "Users", 390);
        SetupNavButton(this.navSettings, "navSettings", "Settings", 428);
        this.navDashboard.Click += new System.EventHandler(this.navDashboard_Click);
        this.navSync.Click += new System.EventHandler(this.navSync_Click);
        this.navBackup.Click += new System.EventHandler(this.navBackup_Click);
        this.navTrash.Click += new System.EventHandler(this.navTrash_Click);
        this.navServers.Click += new System.EventHandler(this.navServers_Click);
        this.navAudit.Click += new System.EventHandler(this.navAudit_Click);
        this.navAnalytics.Click += new System.EventHandler(this.navAnalytics_Click);
        this.navUsers.Click += new System.EventHandler(this.navUsers_Click);
        this.navSettings.Click += new System.EventHandler(this.navSettings_Click);

        this.lblTreeCap = new MaterialSkin.Controls.MaterialLabel();
        this.lblTreeCap.AutoSize = true;
        this.lblTreeCap.Location = new System.Drawing.Point(12, 470);
        this.lblTreeCap.Name = "lblTreeCap";
        this.lblTreeCap.Text = "Files";

        this.treeFiles = new System.Windows.Forms.TreeView();
        this.treeFiles.Location = new System.Drawing.Point(12, 494);
        this.treeFiles.Name = "treeFiles";
        this.treeFiles.Size = new System.Drawing.Size(216, 112);
        this.treeFiles.TabIndex = 2;
        this.treeFiles.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.treeFiles_AfterSelect);
        this.treeFiles.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.treeFiles_DoubleClick);

        this.sideStrip = new System.Windows.Forms.Panel();
        this.sideStrip.Controls.Add(this.btnExpand);
        this.sideStrip.Dock = System.Windows.Forms.DockStyle.Left;
        this.sideStrip.Location = new System.Drawing.Point(0, 0);
        this.sideStrip.Name = "sideStrip";
        this.sideStrip.Size = new System.Drawing.Size(40, 640);
        this.sideStrip.TabIndex = 5;
        this.sideStrip.Visible = false;

        this.btnExpand = new MaterialSkin.Controls.MaterialButton();
        this.btnExpand.AutoSize = false;
        this.btnExpand.HighEmphasis = false;
        this.btnExpand.Location = new System.Drawing.Point(4, 72);
        this.btnExpand.Name = "btnExpand";
        this.btnExpand.Size = new System.Drawing.Size(32, 36);
        this.btnExpand.TabIndex = 0;
        this.btnExpand.Text = "»";
        this.btnExpand.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Text;
        this.btnExpand.UseAccentColor = false;
        this.btnExpand.Click += new System.EventHandler(this.btnExpand_Click);

        this.topSpacer.Dock = System.Windows.Forms.DockStyle.Top;
        this.topSpacer.Location = new System.Drawing.Point(0, 0);
        this.topSpacer.Name = "topSpacer";
        this.topSpacer.Size = new System.Drawing.Size(1210, 64);
        this.topSpacer.TabIndex = 3;

        this.tabSelector.BaseTabControl = this.tabControl;
        this.tabSelector.Dock = System.Windows.Forms.DockStyle.Top;
        this.tabSelector.Location = new System.Drawing.Point(0, 0);
        this.tabSelector.Name = "tabSelector";
        this.tabSelector.Size = new System.Drawing.Size(1210, 48);
        this.tabSelector.TabIndex = 2;

        this.tabControl.Dock = System.Windows.Forms.DockStyle.Fill;
        this.tabControl.Location = new System.Drawing.Point(0, 0);
        this.tabControl.Name = "tabControl";
        this.tabControl.SelectedIndex = 0;
        this.tabControl.Size = new System.Drawing.Size(1210, 640);
        this.tabControl.TabIndex = 0;
        this.tabControl.Controls.Add(this.tabDashboard);
        this.tabControl.Controls.Add(this.tabSync);
        this.tabControl.Controls.Add(this.tabBackup);
        this.tabControl.Controls.Add(this.tabTrash);
        this.tabControl.Controls.Add(this.tabServers);
        this.tabControl.Controls.Add(this.tabAudit);
        this.tabControl.Controls.Add(this.tabAnalytics);
        this.tabControl.Controls.Add(this.tabUsers);
        this.tabControl.Controls.Add(this.tabSettings);

        this.tabDashboard.Controls.Add(this.lblDashTitle);
        this.tabDashboard.Controls.Add(this.cardFiles);
        this.tabDashboard.Controls.Add(this.cardSynced);
        this.tabDashboard.Controls.Add(this.cardPending);
        this.tabDashboard.Controls.Add(this.cardServers);
        this.tabDashboard.Location = new System.Drawing.Point(4, 34);
        this.tabDashboard.Name = "tabDashboard";
        this.tabDashboard.Padding = new System.Windows.Forms.Padding(3);
        this.tabDashboard.Size = new System.Drawing.Size(972, 582);
        this.tabDashboard.TabIndex = 0;
        this.tabDashboard.Text = "Dashboard";

        this.lblDashTitle.AutoSize = true;
        this.lblDashTitle.Location = new System.Drawing.Point(25, 20);
        this.lblDashTitle.Name = "lblDashTitle";
        this.lblDashTitle.Text = "Overview";

        this.lblFilesCap = new MaterialSkin.Controls.MaterialLabel();
        this.lblFilesVal = new System.Windows.Forms.Label();
        this.lblSyncedCap = new MaterialSkin.Controls.MaterialLabel();
        this.lblSyncedVal = new System.Windows.Forms.Label();
        this.lblPendingCap = new MaterialSkin.Controls.MaterialLabel();
        this.lblPendingVal = new System.Windows.Forms.Label();
        this.lblServersCap = new MaterialSkin.Controls.MaterialLabel();
        this.lblServersVal = new System.Windows.Forms.Label();

        this.cardFiles.Location = new System.Drawing.Point(25, 70);
        this.cardFiles.Name = "cardFiles";
        this.cardFiles.Size = new System.Drawing.Size(220, 110);
        this.cardFiles.TabIndex = 1;
        this.lblFilesCap.AutoSize = true;
        this.lblFilesCap.Location = new System.Drawing.Point(15, 15);
        this.lblFilesCap.Name = "lblFilesCap";
        this.lblFilesCap.Text = "All files";
        this.lblFilesVal.AutoSize = true;
        this.lblFilesVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblFilesVal.ForeColor = System.Drawing.Color.FromArgb(0, 90, 158);
        this.lblFilesVal.Location = new System.Drawing.Point(15, 50);
        this.lblFilesVal.Name = "lblFilesVal";
        this.lblFilesVal.Text = "0";
        this.cardFiles.Controls.Add(this.lblFilesCap);
        this.cardFiles.Controls.Add(this.lblFilesVal);

        this.cardSynced.Location = new System.Drawing.Point(268, 70);
        this.cardSynced.Name = "cardSynced";
        this.cardSynced.Size = new System.Drawing.Size(220, 110);
        this.cardSynced.TabIndex = 2;
        this.lblSyncedCap.AutoSize = true;
        this.lblSyncedCap.Location = new System.Drawing.Point(15, 15);
        this.lblSyncedCap.Name = "lblSyncedCap";
        this.lblSyncedCap.Text = "Synced";
        this.lblSyncedVal.AutoSize = true;
        this.lblSyncedVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblSyncedVal.ForeColor = System.Drawing.Color.FromArgb(76, 175, 80);
        this.lblSyncedVal.Location = new System.Drawing.Point(15, 50);
        this.lblSyncedVal.Name = "lblSyncedVal";
        this.lblSyncedVal.Text = "0";
        this.cardSynced.Controls.Add(this.lblSyncedCap);
        this.cardSynced.Controls.Add(this.lblSyncedVal);

        this.cardPending.Location = new System.Drawing.Point(511, 70);
        this.cardPending.Name = "cardPending";
        this.cardPending.Size = new System.Drawing.Size(220, 110);
        this.cardPending.TabIndex = 3;
        this.lblPendingCap.AutoSize = true;
        this.lblPendingCap.Location = new System.Drawing.Point(15, 15);
        this.lblPendingCap.Name = "lblPendingCap";
        this.lblPendingCap.Text = "Pending";
        this.lblPendingVal.AutoSize = true;
        this.lblPendingVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblPendingVal.ForeColor = System.Drawing.Color.FromArgb(255, 193, 7);
        this.lblPendingVal.Location = new System.Drawing.Point(15, 50);
        this.lblPendingVal.Name = "lblPendingVal";
        this.lblPendingVal.Text = "0";
        this.cardPending.Controls.Add(this.lblPendingCap);
        this.cardPending.Controls.Add(this.lblPendingVal);

        this.cardServers.Location = new System.Drawing.Point(754, 70);
        this.cardServers.Name = "cardServers";
        this.cardServers.Size = new System.Drawing.Size(220, 110);
        this.cardServers.TabIndex = 4;
        this.lblServersCap.AutoSize = true;
        this.lblServersCap.Location = new System.Drawing.Point(15, 15);
        this.lblServersCap.Name = "lblServersCap";
        this.lblServersCap.Text = "Servers";
        this.lblServersVal.AutoSize = true;
        this.lblServersVal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
        this.lblServersVal.ForeColor = System.Drawing.Color.FromArgb(0, 90, 158);
        this.lblServersVal.Location = new System.Drawing.Point(15, 50);
        this.lblServersVal.Name = "lblServersVal";
        this.lblServersVal.Text = "0";
        this.cardServers.Controls.Add(this.lblServersCap);
        this.cardServers.Controls.Add(this.lblServersVal);

        this.tabSync.Controls.Add(this.gridFiles);
        this.tabSync.Controls.Add(this.lblStatus);
        this.tabSync.Controls.Add(this.btnSelectFolder);
        this.tabSync.Controls.Add(this.btnSync);
        this.tabSync.Controls.Add(this.btnDelete);
        this.tabSync.Controls.Add(this.btnResume);
        this.tabSync.Controls.Add(this.btnExplorer);
        this.tabSync.Controls.Add(this.btnLogout);
        this.tabSync.Location = new System.Drawing.Point(4, 34);
        this.tabSync.Name = "tabSync";
        this.tabSync.Padding = new System.Windows.Forms.Padding(3);
        this.tabSync.Size = new System.Drawing.Size(972, 582);
        this.tabSync.TabIndex = 0;
        this.tabSync.Text = "Sync";

        this.btnSelectFolder.AutoSize = false;
        this.btnSelectFolder.HighEmphasis = true;
        this.btnSelectFolder.Location = new System.Drawing.Point(15, 15);
        this.btnSelectFolder.Name = "btnSelectFolder";
        this.btnSelectFolder.Size = new System.Drawing.Size(150, 36);
        this.btnSelectFolder.TabIndex = 0;
        this.btnSelectFolder.Text = "Select Folder";
        this.btnSelectFolder.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
        this.btnSelectFolder.UseAccentColor = false;
        this.btnSelectFolder.AccessibleName = "Select folder to scan";

        this.lblStatus.AutoSize = true;
        this.lblStatus.Location = new System.Drawing.Point(510, 62);
        this.lblStatus.Name = "lblStatus";
        this.lblStatus.TabIndex = 1;
        this.lblStatus.Text = "Ready.";

        this.btnSync.AutoSize = false;
        this.btnSync.HighEmphasis = true;
        this.btnSync.Location = new System.Drawing.Point(180, 15);
        this.btnSync.Name = "btnSync";
        this.btnSync.Size = new System.Drawing.Size(110, 36);
        this.btnSync.TabIndex = 3;
        this.btnSync.Text = "Sync";
        this.btnSync.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
        this.btnSync.UseAccentColor = false;
        this.btnSync.AccessibleName = "Synchronize pending files";

        this.btnDelete.AutoSize = false;
        this.btnDelete.HighEmphasis = false;
        this.btnDelete.Location = new System.Drawing.Point(305, 15);
        this.btnDelete.Name = "btnDelete";
        this.btnDelete.Size = new System.Drawing.Size(110, 36);
        this.btnDelete.TabIndex = 4;
        this.btnDelete.Text = "Delete";
        this.btnDelete.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnDelete.UseAccentColor = false;
        this.btnDelete.AccessibleName = "Delete selected file";

        this.btnResume.AutoSize = false;
        this.btnResume.HighEmphasis = false;
        this.btnResume.Location = new System.Drawing.Point(430, 15);
        this.btnResume.Name = "btnResume";
        this.btnResume.Size = new System.Drawing.Size(110, 36);
        this.btnResume.TabIndex = 5;
        this.btnResume.Text = "Resume";
        this.btnResume.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnResume.UseAccentColor = false;
        this.btnResume.AccessibleName = "Resume failed uploads";

        this.btnExplorer.AutoSize = false;
        this.btnExplorer.HighEmphasis = false;
        this.btnExplorer.Location = new System.Drawing.Point(555, 15);
        this.btnExplorer.Name = "btnExplorer";
        this.btnExplorer.Size = new System.Drawing.Size(110, 36);
        this.btnExplorer.TabIndex = 9;
        this.btnExplorer.Text = "Explorer";
        this.btnExplorer.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnExplorer.UseAccentColor = false;
        this.btnExplorer.AccessibleName = "Open file explorer";

        this.btnLogout.AutoSize = false;
        this.btnLogout.HighEmphasis = false;
        this.btnLogout.Location = new System.Drawing.Point(850, 15);
        this.btnLogout.Name = "btnLogout";
        this.btnLogout.Size = new System.Drawing.Size(110, 36);
        this.btnLogout.TabIndex = 6;
        this.btnLogout.Text = "Logout";
        this.btnLogout.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnLogout.UseAccentColor = false;
        this.btnLogout.AccessibleName = "Log out";

        this.notifyIcon.Icon = System.Drawing.SystemIcons.Application;
        this.notifyIcon.Text = "DataSyncEngine";
        this.notifyIcon.Visible = true;

        this.trayMenu = new MaterialSkin.Controls.MaterialContextMenuStrip();
        this.trayShow = new MaterialSkin.Controls.MaterialToolStripMenuItem();
        this.trayExit = new MaterialSkin.Controls.MaterialToolStripMenuItem();
        this.trayMenu.Items.Add(this.trayShow);
        this.trayMenu.Items.Add(this.trayExit);
        this.trayShow.Text = "Show";
        this.trayExit.Text = "Exit";
        this.trayShow.Click += new System.EventHandler(this.trayShow_Click);
        this.trayExit.Click += new System.EventHandler(this.trayExit_Click);
        this.trayAbout = new MaterialSkin.Controls.MaterialToolStripMenuItem();
        this.trayAbout.Text = "About";
        this.trayAbout.Click += new System.EventHandler(this.trayAbout_Click);
        this.trayMenu.Items.Add(this.trayAbout);
        this.notifyIcon.ContextMenuStrip = this.trayMenu;
        this.notifyIcon.DoubleClick += new System.EventHandler(this.trayShow_Click);

        this.statusStrip = new System.Windows.Forms.StatusStrip();
        this.lblServerInfo = new System.Windows.Forms.ToolStripStatusLabel();
        this.statusStrip.Items.Add(this.lblServerInfo);
        this.statusStrip.Location = new System.Drawing.Point(0, 618);
        this.statusStrip.Name = "statusStrip";
        this.statusStrip.Size = new System.Drawing.Size(1210, 22);
        this.statusStrip.TabIndex = 1;
        this.lblServerInfo.Name = "lblServerInfo";
        this.lblServerInfo.Text = "";

        this.btnTheme = new System.Windows.Forms.ToolStripDropDownButton();
        this.themeDarkItem = new System.Windows.Forms.ToolStripMenuItem();
        this.themeLightItem = new System.Windows.Forms.ToolStripMenuItem();
        this.btnTheme.Text = "Theme";
        this.themeDarkItem.Text = "Dark";
        this.themeLightItem.Text = "Light";
        this.btnTheme.DropDownItems.Add(this.themeDarkItem);
        this.btnTheme.DropDownItems.Add(this.themeLightItem);
        this.themeDarkItem.Click += new System.EventHandler(this.themeDarkItem_Click);
        this.themeLightItem.Click += new System.EventHandler(this.themeLightItem_Click);
        this.statusStrip.Items.Add(new System.Windows.Forms.ToolStripSeparator());
        this.statusStrip.Items.Add(this.btnTheme);

        this.txtFilter = new MaterialSkin.Controls.MaterialTextBox2();
        this.txtFilter.Hint = "Type to filter files...";
        this.txtFilter.Location = new System.Drawing.Point(15, 58);
        this.txtFilter.MaxLength = 32767;
        this.txtFilter.Name = "txtFilter";
        this.txtFilter.Size = new System.Drawing.Size(250, 36);
        this.txtFilter.TabIndex = 7;
        this.txtFilter.UseTallSize = false;
        this.txtFilter.AccessibleName = "Filter files";
        this.txtFilter.TextChanged += new System.EventHandler(this.txtFilter_TextChanged);
        this.tabSync.Controls.Add(this.txtFilter);

        this.progressBar = new MaterialSkin.Controls.MaterialProgressBar();
        this.progressBar.Location = new System.Drawing.Point(280, 61);
        this.progressBar.Name = "progressBar";
        this.progressBar.Size = new System.Drawing.Size(210, 20);
        this.progressBar.TabIndex = 8;
        this.tabSync.Controls.Add(this.progressBar);

        this.gridFiles.Location = new System.Drawing.Point(15, 95);
        this.gridFiles.Size = new System.Drawing.Size(940, 465);

        this.Controls.Add(this.statusStrip);

        this.gridFiles.AllowUserToAddRows = false;
        this.gridFiles.AllowUserToDeleteRows = false;
        this.gridFiles.ReadOnly = true;
        this.gridFiles.Name = "gridFiles";
        this.gridFiles.TabIndex = 2;

        this.tabBackup.Location = new System.Drawing.Point(4, 34);
        this.tabBackup.Name = "tabBackup";
        this.tabBackup.Padding = new System.Windows.Forms.Padding(3);
        this.tabBackup.Size = new System.Drawing.Size(972, 582);
        this.tabBackup.TabIndex = 5;
        this.tabBackup.Text = "Backup";

        this.lblBackupTitle = new MaterialSkin.Controls.MaterialLabel();
        this.lblBackupTitle.AutoSize = true;
        this.lblBackupTitle.Location = new System.Drawing.Point(20, 20);
        this.lblBackupTitle.Name = "lblBackupTitle";
        this.lblBackupTitle.Text = "Server backup (export decrypted files)";
        this.tabBackup.Controls.Add(this.lblBackupTitle);

        this.btnBackupNow = new MaterialSkin.Controls.MaterialButton();
        this.btnBackupNow.AutoSize = false;
        this.btnBackupNow.HighEmphasis = true;
        this.btnBackupNow.Location = new System.Drawing.Point(20, 60);
        this.btnBackupNow.Name = "btnBackupNow";
        this.btnBackupNow.Size = new System.Drawing.Size(220, 36);
        this.btnBackupNow.TabIndex = 0;
        this.btnBackupNow.Text = "Backup Now";
        this.btnBackupNow.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
        this.btnBackupNow.UseAccentColor = false;
        this.btnBackupNow.AccessibleName = "Export all server files to a folder";
        this.btnBackupNow.Click += new System.EventHandler(this.btnBackupNow_Click);
        this.tabBackup.Controls.Add(this.btnBackupNow);

        this.lblBackupInfo = new MaterialSkin.Controls.MaterialLabel();
        this.lblBackupInfo.AutoSize = true;
        this.lblBackupInfo.Location = new System.Drawing.Point(20, 115);
        this.lblBackupInfo.Name = "lblBackupInfo";
        this.lblBackupInfo.Text = "No backup yet.";
        this.tabBackup.Controls.Add(this.lblBackupInfo);

        this.lblLastBackup = new MaterialSkin.Controls.MaterialLabel();
        this.lblLastBackup.AutoSize = true;
        this.lblLastBackup.Location = new System.Drawing.Point(20, 150);
        this.lblLastBackup.Name = "lblLastBackup";
        this.lblLastBackup.Text = "";
        this.tabBackup.Controls.Add(this.lblLastBackup);

        this.tabTrash.Location = new System.Drawing.Point(4, 34);
        this.tabTrash.Name = "tabTrash";
        this.tabTrash.Padding = new System.Windows.Forms.Padding(3);
        this.tabTrash.Size = new System.Drawing.Size(972, 582);
        this.tabTrash.TabIndex = 6;
        this.tabTrash.Text = "Trash";

        this.btnRestore = new MaterialSkin.Controls.MaterialButton();
        this.btnRestore.AutoSize = false;
        this.btnRestore.HighEmphasis = true;
        this.btnRestore.Location = new System.Drawing.Point(15, 15);
        this.btnRestore.Name = "btnRestore";
        this.btnRestore.Size = new System.Drawing.Size(140, 36);
        this.btnRestore.TabIndex = 0;
        this.btnRestore.Text = "Restore";
        this.btnRestore.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
        this.btnRestore.UseAccentColor = false;
        this.btnRestore.AccessibleName = "Restore selected deleted file";
        this.btnRestore.Click += new System.EventHandler(this.btnRestore_Click);
        this.tabTrash.Controls.Add(this.btnRestore);

        this.btnPurge = new MaterialSkin.Controls.MaterialButton();
        this.btnPurge.AutoSize = false;
        this.btnPurge.HighEmphasis = false;
        this.btnPurge.Location = new System.Drawing.Point(170, 15);
        this.btnPurge.Name = "btnPurge";
        this.btnPurge.Size = new System.Drawing.Size(140, 36);
        this.btnPurge.TabIndex = 1;
        this.btnPurge.Text = "Delete Forever";
        this.btnPurge.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnPurge.UseAccentColor = false;
        this.btnPurge.AccessibleName = "Permanently delete selected file";
        this.btnPurge.Click += new System.EventHandler(this.btnPurge_Click);
        this.tabTrash.Controls.Add(this.btnPurge);

        this.lblTrashInfo = new MaterialSkin.Controls.MaterialLabel();
        this.lblTrashInfo.AutoSize = true;
        this.lblTrashInfo.Location = new System.Drawing.Point(330, 24);
        this.lblTrashInfo.Name = "lblTrashInfo";
        this.lblTrashInfo.Text = "Deleted files can be restored here.";
        this.tabTrash.Controls.Add(this.lblTrashInfo);

        this.gridTrash = new System.Windows.Forms.DataGridView();
        this.gridTrash.AllowUserToAddRows = false;
        this.gridTrash.AllowUserToDeleteRows = false;
        this.gridTrash.ReadOnly = true;
        this.gridTrash.Location = new System.Drawing.Point(15, 60);
        this.gridTrash.Name = "gridTrash";
        this.gridTrash.Size = new System.Drawing.Size(940, 500);
        this.gridTrash.TabIndex = 2;
        this.tabTrash.Controls.Add(this.gridTrash);

        this.tabServers.Controls.Add(this.gridServers);
        this.tabServers.Controls.Add(this.btnAddServer);
        this.tabServers.Location = new System.Drawing.Point(4, 34);
        this.tabServers.Name = "tabServers";
        this.tabServers.Size = new System.Drawing.Size(972, 582);
        this.tabServers.TabIndex = 1;
        this.tabServers.Text = "Servers";

        this.btnAddServer.AutoSize = false;
        this.btnAddServer.HighEmphasis = true;
        this.btnAddServer.Location = new System.Drawing.Point(15, 15);
        this.btnAddServer.Name = "btnAddServer";
        this.btnAddServer.Size = new System.Drawing.Size(150, 36);
        this.btnAddServer.TabIndex = 0;
        this.btnAddServer.Text = "Add Server";
        this.btnAddServer.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
        this.btnAddServer.UseAccentColor = false;

        this.btnEditServer.AutoSize = false;
        this.btnEditServer.HighEmphasis = false;
        this.btnEditServer.Location = new System.Drawing.Point(180, 15);
        this.btnEditServer.Name = "btnEditServer";
        this.btnEditServer.Size = new System.Drawing.Size(140, 36);
        this.btnEditServer.TabIndex = 2;
        this.btnEditServer.Text = "Edit Server";
        this.btnEditServer.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnEditServer.UseAccentColor = false;

        this.btnSetActive.AutoSize = false;
        this.btnSetActive.HighEmphasis = false;
        this.btnSetActive.Location = new System.Drawing.Point(335, 15);
        this.btnSetActive.Name = "btnSetActive";
        this.btnSetActive.Size = new System.Drawing.Size(140, 36);
        this.btnSetActive.TabIndex = 3;
        this.btnSetActive.Text = "Set Active";
        this.btnSetActive.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnSetActive.UseAccentColor = false;

        this.btnDeleteServer.AutoSize = false;
        this.btnDeleteServer.HighEmphasis = false;
        this.btnDeleteServer.Location = new System.Drawing.Point(490, 15);
        this.btnDeleteServer.Name = "btnDeleteServer";
        this.btnDeleteServer.Size = new System.Drawing.Size(140, 36);
        this.btnDeleteServer.TabIndex = 4;
        this.btnDeleteServer.Text = "Delete Server";
        this.btnDeleteServer.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnDeleteServer.UseAccentColor = false;

        this.tabServers.Controls.Add(this.btnEditServer);
        this.tabServers.Controls.Add(this.btnSetActive);
        this.tabServers.Controls.Add(this.btnDeleteServer);

        this.gridServers.AllowUserToAddRows = false;
        this.gridServers.AllowUserToDeleteRows = false;
        this.gridServers.ReadOnly = true;
        this.gridServers.Location = new System.Drawing.Point(15, 60);
        this.gridServers.Name = "gridServers";
        this.gridServers.Size = new System.Drawing.Size(940, 500);
        this.gridServers.TabIndex = 1;

        this.tabAudit.Controls.Add(this.gridAudit);
        this.tabAudit.Location = new System.Drawing.Point(4, 34);
        this.tabAudit.Name = "tabAudit";
        this.tabAudit.Size = new System.Drawing.Size(972, 582);
        this.tabAudit.TabIndex = 2;
        this.tabAudit.Text = "Audit";

        this.gridAudit.AllowUserToAddRows = false;
        this.gridAudit.AllowUserToDeleteRows = false;
        this.gridAudit.ReadOnly = true;
        this.gridAudit.Dock = System.Windows.Forms.DockStyle.Fill;
        this.gridAudit.Name = "gridAudit";
        this.gridAudit.TabIndex = 0;

        this.tabAnalytics.Controls.Add(this.lblAnalytics);
        this.tabAnalytics.Location = new System.Drawing.Point(4, 34);
        this.tabAnalytics.Name = "tabAnalytics";
        this.tabAnalytics.Size = new System.Drawing.Size(972, 582);
        this.tabAnalytics.TabIndex = 3;
        this.tabAnalytics.Text = "Analytics";

        this.lblAnalytics = new MaterialSkin.Controls.MaterialLabel();
        this.lblAnalytics.AutoSize = true;
        this.lblAnalytics.Location = new System.Drawing.Point(20, 20);
        this.lblAnalytics.Name = "lblAnalytics";
        this.lblAnalytics.Text = "Analytics dashboard (Admin only).";

        this.lblAnaTotal = new MaterialSkin.Controls.MaterialLabel();
        this.lblAnaSynced = new MaterialSkin.Controls.MaterialLabel();
        this.lblAnaPending = new MaterialSkin.Controls.MaterialLabel();
        this.lblAnaModified = new MaterialSkin.Controls.MaterialLabel();
        this.lblAnaBytes = new MaterialSkin.Controls.MaterialLabel();
        this.lblAnaTotal.AutoSize = true;
        this.lblAnaTotal.Location = new System.Drawing.Point(20, 60);
        this.lblAnaTotal.Name = "lblAnaTotal";
        this.lblAnaTotal.Text = "Total files: 0";
        this.lblAnaSynced.AutoSize = true;
        this.lblAnaSynced.Location = new System.Drawing.Point(20, 90);
        this.lblAnaSynced.Name = "lblAnaSynced";
        this.lblAnaSynced.Text = "Synced: 0";
        this.lblAnaPending.AutoSize = true;
        this.lblAnaPending.Location = new System.Drawing.Point(20, 120);
        this.lblAnaPending.Name = "lblAnaPending";
        this.lblAnaPending.Text = "Pending: 0";
        this.lblAnaModified.AutoSize = true;
        this.lblAnaModified.Location = new System.Drawing.Point(20, 150);
        this.lblAnaModified.Name = "lblAnaModified";
        this.lblAnaModified.Text = "Modified: 0";
        this.lblAnaBytes.AutoSize = true;
        this.lblAnaBytes.Location = new System.Drawing.Point(20, 180);
        this.lblAnaBytes.Name = "lblAnaBytes";
        this.lblAnaBytes.Text = "Total size: 0 bytes";
        this.tabAnalytics.Controls.Add(this.lblAnaTotal);
        this.tabAnalytics.Controls.Add(this.lblAnaSynced);
        this.tabAnalytics.Controls.Add(this.lblAnaPending);
        this.tabAnalytics.Controls.Add(this.lblAnaModified);
        this.tabAnalytics.Controls.Add(this.lblAnaBytes);

        this.tabSettings.Location = new System.Drawing.Point(4, 34);
        this.tabSettings.Name = "tabSettings";
        this.tabSettings.Padding = new System.Windows.Forms.Padding(3);
        this.tabSettings.Size = new System.Drawing.Size(972, 582);
        this.tabSettings.TabIndex = 7;
        this.tabSettings.Text = "Settings";

        this.lblSetTheme = new MaterialSkin.Controls.MaterialLabel();
        this.lblSetTheme.AutoSize = true;
        this.lblSetTheme.Location = new System.Drawing.Point(20, 20);
        this.lblSetTheme.Name = "lblSetTheme";
        this.lblSetTheme.Text = "Theme";
        this.tabSettings.Controls.Add(this.lblSetTheme);

        this.radDark = new MaterialSkin.Controls.MaterialRadioButton();
        this.radDark.AutoSize = true;
        this.radDark.Location = new System.Drawing.Point(20, 50);
        this.radDark.Name = "radDark";
        this.radDark.Size = new System.Drawing.Size(80, 37);
        this.radDark.TabIndex = 0;
        this.radDark.Text = "Dark";
        this.radDark.CheckedChanged += new System.EventHandler(this.radDark_CheckedChanged);
        this.tabSettings.Controls.Add(this.radDark);

        this.radLight = new MaterialSkin.Controls.MaterialRadioButton();
        this.radLight.AutoSize = true;
        this.radLight.Location = new System.Drawing.Point(140, 50);
        this.radLight.Name = "radLight";
        this.radLight.Size = new System.Drawing.Size(80, 37);
        this.radLight.TabIndex = 1;
        this.radLight.Text = "Light";
        this.radLight.CheckedChanged += new System.EventHandler(this.radLight_CheckedChanged);
        this.tabSettings.Controls.Add(this.radLight);

        this.lblSetFont = new MaterialSkin.Controls.MaterialLabel();
        this.lblSetFont.AutoSize = true;
        this.lblSetFont.Location = new System.Drawing.Point(20, 105);
        this.lblSetFont.Name = "lblSetFont";
        this.lblSetFont.Text = "Font size";
        this.tabSettings.Controls.Add(this.lblSetFont);

        this.trkFontSize = new System.Windows.Forms.TrackBar();
        ((System.ComponentModel.ISupportInitialize)(this.trkFontSize)).BeginInit();
        this.trkFontSize.Location = new System.Drawing.Point(20, 135);
        this.trkFontSize.Minimum = 8;
        this.trkFontSize.Maximum = 16;
        this.trkFontSize.Name = "trkFontSize";
        this.trkFontSize.Size = new System.Drawing.Size(250, 45);
        this.trkFontSize.TabIndex = 2;
        this.trkFontSize.ValueChanged += new System.EventHandler(this.trkFontSize_ValueChanged);
        ((System.ComponentModel.ISupportInitialize)(this.trkFontSize)).EndInit();
        this.tabSettings.Controls.Add(this.trkFontSize);

        this.lblFontSizeVal = new MaterialSkin.Controls.MaterialLabel();
        this.lblFontSizeVal.AutoSize = true;
        this.lblFontSizeVal.Location = new System.Drawing.Point(280, 145);
        this.lblFontSizeVal.Name = "lblFontSizeVal";
        this.lblFontSizeVal.Text = "9.5";
        this.tabSettings.Controls.Add(this.lblFontSizeVal);

        this.lblFontPreview = new MaterialSkin.Controls.MaterialLabel();
        this.lblFontPreview.AutoSize = true;
        this.lblFontPreview.Location = new System.Drawing.Point(20, 185);
        this.lblFontPreview.Name = "lblFontPreview";
        this.lblFontPreview.Text = "AaBbCcDd 123";
        this.tabSettings.Controls.Add(this.lblFontPreview);

        this.chkBold = new MaterialSkin.Controls.MaterialCheckbox();
        this.chkBold.AutoSize = true;
        this.chkBold.Location = new System.Drawing.Point(20, 220);
        this.chkBold.Name = "chkBold";
        this.chkBold.Size = new System.Drawing.Size(130, 37);
        this.chkBold.TabIndex = 3;
        this.chkBold.Text = "Bold text";
        this.chkBold.CheckedChanged += new System.EventHandler(this.chkBold_CheckedChanged);
        this.tabSettings.Controls.Add(this.chkBold);

        this.lblSetAccent = new MaterialSkin.Controls.MaterialLabel();
        this.lblSetAccent.AutoSize = true;
        this.lblSetAccent.Location = new System.Drawing.Point(20, 270);
        this.lblSetAccent.Name = "lblSetAccent";
        this.lblSetAccent.Text = "Accent color";
        this.tabSettings.Controls.Add(this.lblSetAccent);

        this.cmbAccent = new MaterialSkin.Controls.MaterialComboBox();
        this.cmbAccent.AutoResize = false;
        this.cmbAccent.Hint = "Accent";
        this.cmbAccent.Location = new System.Drawing.Point(20, 300);
        this.cmbAccent.Name = "cmbAccent";
        this.cmbAccent.Size = new System.Drawing.Size(250, 48);
        this.cmbAccent.TabIndex = 4;
        this.cmbAccent.SelectedIndexChanged += new System.EventHandler(this.cmbAccent_SelectedIndexChanged);
        this.tabSettings.Controls.Add(this.cmbAccent);

        this.swAnimations = new MaterialSkin.Controls.MaterialSwitch();
        this.swAnimations.AutoSize = true;
        this.swAnimations.Location = new System.Drawing.Point(480, 50);
        this.swAnimations.Name = "swAnimations";
        this.swAnimations.Size = new System.Drawing.Size(200, 37);
        this.swAnimations.TabIndex = 5;
        this.swAnimations.Text = "Animations";
        this.swAnimations.CheckedChanged += new System.EventHandler(this.swAnimations_CheckedChanged);
        this.tabSettings.Controls.Add(this.swAnimations);

        this.swConfirmDelete = new MaterialSkin.Controls.MaterialSwitch();
        this.swConfirmDelete.AutoSize = true;
        this.swConfirmDelete.Location = new System.Drawing.Point(480, 100);
        this.swConfirmDelete.Name = "swConfirmDelete";
        this.swConfirmDelete.Size = new System.Drawing.Size(240, 37);
        this.swConfirmDelete.TabIndex = 6;
        this.swConfirmDelete.Text = "Confirm before delete";
        this.swConfirmDelete.CheckedChanged += new System.EventHandler(this.swConfirmDelete_CheckedChanged);
        this.tabSettings.Controls.Add(this.swConfirmDelete);

        this.swNotifications = new MaterialSkin.Controls.MaterialSwitch();
        this.swNotifications.AutoSize = true;
        this.swNotifications.Location = new System.Drawing.Point(480, 150);
        this.swNotifications.Name = "swNotifications";
        this.swNotifications.Size = new System.Drawing.Size(220, 37);
        this.swNotifications.TabIndex = 7;
        this.swNotifications.Text = "Tray notifications";
        this.swNotifications.CheckedChanged += new System.EventHandler(this.swNotifications_CheckedChanged);
        this.tabSettings.Controls.Add(this.swNotifications);

        this.swColdStorage = new MaterialSkin.Controls.MaterialSwitch();
        this.swColdStorage.AutoSize = true;
        this.swColdStorage.Location = new System.Drawing.Point(480, 200);
        this.swColdStorage.Name = "swColdStorage";
        this.swColdStorage.Size = new System.Drawing.Size(260, 37);
        this.swColdStorage.TabIndex = 8;
        this.swColdStorage.Text = "Keep local cold copy";
        this.swColdStorage.CheckedChanged += new System.EventHandler(this.swColdStorage_CheckedChanged);
        this.tabSettings.Controls.Add(this.swColdStorage);

        this.swMinimizeToTray = new MaterialSkin.Controls.MaterialSwitch();
        this.swMinimizeToTray.AutoSize = true;
        this.swMinimizeToTray.Location = new System.Drawing.Point(480, 250);
        this.swMinimizeToTray.Name = "swMinimizeToTray";
        this.swMinimizeToTray.Size = new System.Drawing.Size(240, 37);
        this.swMinimizeToTray.TabIndex = 9;
        this.swMinimizeToTray.Text = "Minimize to tray";
        this.swMinimizeToTray.CheckedChanged += new System.EventHandler(this.swMinimizeToTray_CheckedChanged);
        this.tabSettings.Controls.Add(this.swMinimizeToTray);

        this.btnResetSettings = new MaterialSkin.Controls.MaterialButton();
        this.btnResetSettings.AutoSize = false;
        this.btnResetSettings.HighEmphasis = false;
        this.btnResetSettings.Location = new System.Drawing.Point(480, 310);
        this.btnResetSettings.Name = "btnResetSettings";
        this.btnResetSettings.Size = new System.Drawing.Size(200, 36);
        this.btnResetSettings.TabIndex = 10;
        this.btnResetSettings.Text = "Reset Defaults";
        this.btnResetSettings.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnResetSettings.UseAccentColor = false;
        this.btnResetSettings.Click += new System.EventHandler(this.btnResetSettings_Click);
        this.tabSettings.Controls.Add(this.btnResetSettings);

        this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(1210, 640);
        this.Controls.Add(this.tabControl);
        this.Controls.Add(this.tabSelector);
        this.Controls.Add(this.topSpacer);
        this.Controls.Add(this.sideBar);
        this.Controls.Add(this.sideStrip);
        this.Name = "MainView";
        this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        this.Text = "DataSyncEngine";
        this.KeyPreview = true;
        this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.MainView_KeyDown);

        this.toolTip = new System.Windows.Forms.ToolTip(this.components);
        this.toolTip.SetToolTip(this.btnSelectFolder, "Choose a folder to scan");
        this.toolTip.SetToolTip(this.btnSync, "Upload pending files (Ctrl+S)");
        this.toolTip.SetToolTip(this.btnDelete, "Delete the selected file (Del)");
        this.toolTip.SetToolTip(this.btnResume, "Resume failed uploads");
        this.toolTip.SetToolTip(this.btnExplorer, "Open the file explorer");
        this.toolTip.SetToolTip(this.btnLogout, "Log out of the application");
        this.toolTip.SetToolTip(this.txtFilter, "Type to filter files (Ctrl+F)");
        this.toolTip.SetToolTip(this.progressBar, "Synchronization progress");
        this.toolTip.SetToolTip(this.btnBackupNow, "Export all server files to a folder");
        this.toolTip.SetToolTip(this.btnRestore, "Restore the selected deleted file");
        this.tabControl.ResumeLayout(false);
        this.tabSync.ResumeLayout(false);
        this.tabSync.PerformLayout();
        this.tabServers.ResumeLayout(false);
        this.tabServers.PerformLayout();
        this.tabAudit.ResumeLayout(false);
        this.tabAnalytics.ResumeLayout(false);
        this.tabAnalytics.PerformLayout();

        this.tabUsers.SuspendLayout();
        this.tabUsers.Controls.Add(this.gridUsers);
        this.tabUsers.Controls.Add(this.btnAddUser);
        this.tabUsers.Controls.Add(this.btnDeleteUser);
        this.tabUsers.Location = new System.Drawing.Point(4, 34);
        this.tabUsers.Name = "tabUsers";
        this.tabUsers.Size = new System.Drawing.Size(972, 582);
        this.tabUsers.TabIndex = 4;
        this.tabUsers.Text = "Users";

        this.btnAddUser.AutoSize = false;
        this.btnAddUser.HighEmphasis = true;
        this.btnAddUser.Location = new System.Drawing.Point(15, 15);
        this.btnAddUser.Name = "btnAddUser";
        this.btnAddUser.Size = new System.Drawing.Size(140, 36);
        this.btnAddUser.TabIndex = 0;
        this.btnAddUser.Text = "Add User";
        this.btnAddUser.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
        this.btnAddUser.UseAccentColor = false;

        this.btnDeleteUser.AutoSize = false;
        this.btnDeleteUser.HighEmphasis = false;
        this.btnDeleteUser.Location = new System.Drawing.Point(170, 15);
        this.btnDeleteUser.Name = "btnDeleteUser";
        this.btnDeleteUser.Size = new System.Drawing.Size(140, 36);
        this.btnDeleteUser.TabIndex = 1;
        this.btnDeleteUser.Text = "Delete User";
        this.btnDeleteUser.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
        this.btnDeleteUser.UseAccentColor = false;

        this.gridUsers.AllowUserToAddRows = false;
        this.gridUsers.AllowUserToDeleteRows = false;
        this.gridUsers.ReadOnly = true;
        this.gridUsers.Location = new System.Drawing.Point(15, 60);
        this.gridUsers.Name = "gridUsers";
        this.gridUsers.Size = new System.Drawing.Size(940, 500);
        this.gridUsers.TabIndex = 2;
        this.tabUsers.ResumeLayout(false);

        ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridFiles)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridServers)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridAudit)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.gridTrash)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.trkFontSize)).EndInit();
        this.tabBackup.ResumeLayout(false);
        this.tabTrash.ResumeLayout(false);
        this.tabTrash.PerformLayout();
        this.tabSettings.ResumeLayout(false);
        this.tabSettings.PerformLayout();
        this.sideBar.ResumeLayout(false);
        this.sideBar.PerformLayout();
        this.sideStrip.ResumeLayout(false);
        this.ResumeLayout(false);
    }

    private MaterialSkin.Controls.MaterialTabControl tabControl;
    private MaterialSkin.Controls.MaterialTabSelector tabSelector;
    private System.Windows.Forms.Panel topSpacer;
    private System.Windows.Forms.Panel sideBar;
    private System.Windows.Forms.Panel sideStrip;
    private System.Windows.Forms.PictureBox picSideLogo;
    private MaterialSkin.Controls.MaterialLabel lblSideTitle;
    private MaterialSkin.Controls.MaterialButton btnNavToggle;
    private MaterialSkin.Controls.MaterialButton btnExpand;
    private MaterialSkin.Controls.MaterialButton navDashboard;
    private MaterialSkin.Controls.MaterialButton navSync;
    private MaterialSkin.Controls.MaterialButton navBackup;
    private MaterialSkin.Controls.MaterialButton navTrash;
    private MaterialSkin.Controls.MaterialButton navServers;
    private MaterialSkin.Controls.MaterialButton navAudit;
    private MaterialSkin.Controls.MaterialButton navAnalytics;
    private MaterialSkin.Controls.MaterialButton navUsers;
    private MaterialSkin.Controls.MaterialButton navSettings;
    private MaterialSkin.Controls.MaterialLabel lblTreeCap;
    private System.Windows.Forms.TreeView treeFiles;
    private System.Windows.Forms.TabPage tabDashboard;
    private System.Windows.Forms.TabPage tabSync;
    private System.Windows.Forms.TabPage tabBackup;
    private MaterialSkin.Controls.MaterialLabel lblBackupTitle;
    private MaterialSkin.Controls.MaterialButton btnBackupNow;
    private MaterialSkin.Controls.MaterialLabel lblBackupInfo;
    private MaterialSkin.Controls.MaterialLabel lblLastBackup;
    private System.Windows.Forms.TabPage tabTrash;
    private MaterialSkin.Controls.MaterialButton btnRestore;
    private MaterialSkin.Controls.MaterialButton btnPurge;
    private MaterialSkin.Controls.MaterialLabel lblTrashInfo;
    private System.Windows.Forms.DataGridView gridTrash;
    private System.Windows.Forms.TabPage tabSettings;
    private MaterialSkin.Controls.MaterialLabel lblSetTheme;
    private MaterialSkin.Controls.MaterialRadioButton radDark;
    private MaterialSkin.Controls.MaterialRadioButton radLight;
    private MaterialSkin.Controls.MaterialLabel lblSetFont;
    private System.Windows.Forms.TrackBar trkFontSize;
    private MaterialSkin.Controls.MaterialLabel lblFontSizeVal;
    private MaterialSkin.Controls.MaterialLabel lblFontPreview;
    private MaterialSkin.Controls.MaterialCheckbox chkBold;
    private MaterialSkin.Controls.MaterialLabel lblSetAccent;
    private MaterialSkin.Controls.MaterialComboBox cmbAccent;
    private MaterialSkin.Controls.MaterialSwitch swAnimations;
    private MaterialSkin.Controls.MaterialSwitch swConfirmDelete;
    private MaterialSkin.Controls.MaterialSwitch swNotifications;
    private MaterialSkin.Controls.MaterialSwitch swColdStorage;
    private MaterialSkin.Controls.MaterialSwitch swMinimizeToTray;
    private MaterialSkin.Controls.MaterialButton btnResetSettings;
    private MaterialSkin.Controls.MaterialCard cardFiles;
    private MaterialSkin.Controls.MaterialLabel lblFilesCap;
    private System.Windows.Forms.Label lblFilesVal;
    private MaterialSkin.Controls.MaterialCard cardSynced;
    private MaterialSkin.Controls.MaterialLabel lblSyncedCap;
    private System.Windows.Forms.Label lblSyncedVal;
    private MaterialSkin.Controls.MaterialCard cardPending;
    private MaterialSkin.Controls.MaterialLabel lblPendingCap;
    private System.Windows.Forms.Label lblPendingVal;
    private MaterialSkin.Controls.MaterialCard cardServers;
    private MaterialSkin.Controls.MaterialLabel lblServersCap;
    private System.Windows.Forms.Label lblServersVal;
    private MaterialSkin.Controls.MaterialLabel lblDashTitle;
    private System.Windows.Forms.TabPage tabServers;
    private System.Windows.Forms.TabPage tabAudit;
    private System.Windows.Forms.TabPage tabAnalytics;
    private MaterialSkin.Controls.MaterialButton btnSelectFolder;
    private MaterialSkin.Controls.MaterialButton btnSync;
    private MaterialSkin.Controls.MaterialButton btnDelete;
    private MaterialSkin.Controls.MaterialButton btnResume;
    private MaterialSkin.Controls.MaterialButton btnExplorer;
    private MaterialSkin.Controls.MaterialButton btnLogout;
    private MaterialSkin.Controls.MaterialButton btnAddUser;
    private MaterialSkin.Controls.MaterialButton btnDeleteUser;
    private System.Windows.Forms.DataGridView gridUsers;
    private System.Windows.Forms.TabPage tabUsers;
    private MaterialSkin.Controls.MaterialButton btnEditServer;
    private MaterialSkin.Controls.MaterialButton btnSetActive;
    private MaterialSkin.Controls.MaterialButton btnDeleteServer;
    private System.Windows.Forms.StatusStrip statusStrip;
    private System.Windows.Forms.ToolStripStatusLabel lblServerInfo;
    private System.Windows.Forms.ToolStripDropDownButton btnTheme;
    private System.Windows.Forms.ToolStripMenuItem themeDarkItem;
    private System.Windows.Forms.ToolStripMenuItem themeLightItem;
    private MaterialSkin.Controls.MaterialTextBox2 txtFilter;
    private MaterialSkin.Controls.MaterialProgressBar progressBar;
    private System.Windows.Forms.ToolTip toolTip;
    private MaterialSkin.Controls.MaterialToolStripMenuItem trayAbout;
    private MaterialSkin.Controls.MaterialContextMenuStrip trayMenu;
    private MaterialSkin.Controls.MaterialToolStripMenuItem trayShow;
    private MaterialSkin.Controls.MaterialToolStripMenuItem trayExit;
    private System.Windows.Forms.NotifyIcon notifyIcon;
    private MaterialSkin.Controls.MaterialLabel lblStatus;
    private System.Windows.Forms.DataGridView gridFiles;
    private MaterialSkin.Controls.MaterialButton btnAddServer;
    private System.Windows.Forms.DataGridView gridServers;
    private System.Windows.Forms.DataGridView gridAudit;
    private MaterialSkin.Controls.MaterialLabel lblAnalytics;
    private MaterialSkin.Controls.MaterialLabel lblAnaTotal;
    private MaterialSkin.Controls.MaterialLabel lblAnaSynced;
    private MaterialSkin.Controls.MaterialLabel lblAnaPending;
    private MaterialSkin.Controls.MaterialLabel lblAnaModified;
    private MaterialSkin.Controls.MaterialLabel lblAnaBytes;
}
